/**
 * Auto-generated NBA player image mappings.
 * Maps normalized player names to their local image files.
 *
 * Generated from: assets/images/nba-players/{team-code}/{player_name}.png
 * Total players: 733
 * Total image files: 854
 */

// Team abbreviation mapping (uppercase API codes -> lowercase folder names)
const TEAM_ABBREV_MAP: { [key: string]: string } = {
  ATL: "atl", BOS: "bos", BKN: "bkn", CHA: "cha", CHI: "chi",
  CLE: "cle", DAL: "dal", DEN: "den", DET: "det", GSW: "gsw",
  HOU: "hou", IND: "ind", LAC: "lac", LAL: "lal", MEM: "mem",
  MIA: "mia", MIL: "mil", MIN: "min", NOP: "nop", NYK: "nyk",
  OKC: "okc", ORL: "orl", PHI: "phi", PHX: "phx", POR: "por",
  SAC: "sac", SAS: "sas", TOR: "tor", UTA: "uta", WAS: "was",
};

/**
 * Normalize a player name to match the filename format.
 * "LeBron James" -> "lebron_james"
 * "Luka Doncic" -> "luka_doncic"
 * "Dennis Schroder" -> "dennis_schroder"
 * "Nikola Jokic" -> "nikola_jokic"
 * "PJ Washington Jr." -> "pj_washington_jr"
 */
const normalizePlayerName = (name: string): string => {
  return name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // strip accents
    .toLowerCase()
    .replace(/\./g, "")              // remove periods ("Jr." -> "Jr" -> "jr")
    .replace(/[^a-z0-9\s]/g, "")     // remove non-alphanumeric (except spaces)
    .replace(/\s+/g, "_")            // spaces to underscores
    .replace(/_+/g, "_")             // collapse multiple underscores
    .replace(/^_|_$/g, "");           // trim leading/trailing underscores
};

/**
 * Static map of all NBA player images.
 * Key: normalized player name (lowercase, underscores)
 * Value: array of { team, image } for each team folder containing that player
 */
const PLAYER_IMAGES: { [normalizedName: string]: { team: string; image: any }[] } = {
  "a__estrada": [{ team: "det", image: require("../assets/images/nba-players/det/a__estrada.png") }],
  "a__flagler": [{ team: "okc", image: require("../assets/images/nba-players/okc/a__flagler.png") }],
  "a__reese": [{ team: "okc", image: require("../assets/images/nba-players/okc/a__reese.png") }],
  "a_j__green": [{ team: "mil", image: require("../assets/images/nba-players/mil/a_j__green.png") }],
  "a_j__lawson": [{ team: "dal", image: require("../assets/images/nba-players/dal/a_j__lawson.png") }],
  "aaron_gordon": [{ team: "den", image: require("../assets/images/nba-players/den/aaron_gordon.png") }],
  "aaron_holiday": [{ team: "hou", image: require("../assets/images/nba-players/hou/aaron_holiday.png") }],
  "aaron_nesmith": [{ team: "ind", image: require("../assets/images/nba-players/ind/aaron_nesmith.png") }],
  "aaron_wiggins": [{ team: "okc", image: require("../assets/images/nba-players/okc/aaron_wiggins.png") }],
  "ace_bailey": [{ team: "uta", image: require("../assets/images/nba-players/uta/ace_bailey.png") }],
  "adama_sanogo": [{ team: "chi", image: require("../assets/images/nba-players/chi/adama_sanogo.png") }],
  "adem_bona": [{ team: "phi", image: require("../assets/images/nba-players/phi/adem_bona.png") }],
  "adou_thiero": [{ team: "lal", image: require("../assets/images/nba-players/lal/adou_thiero.png") }],
  "aj_green": [{ team: "mil", image: require("../assets/images/nba-players/mil/aj_green.png") }],
  "aj_johnson": [{ team: "mil", image: require("../assets/images/nba-players/mil/aj_johnson.png") }, { team: "was", image: require("../assets/images/nba-players/was/aj_johnson.png") }],
  "aj_lawson": [{ team: "tor", image: require("../assets/images/nba-players/tor/aj_lawson.png") }],
  "ajay_mitchell": [{ team: "okc", image: require("../assets/images/nba-players/okc/ajay_mitchell.png") }],
  "al_horford": [{ team: "bos", image: require("../assets/images/nba-players/bos/al_horford.png") }, { team: "gsw", image: require("../assets/images/nba-players/gsw/al_horford.png") }],
  "alec_burks": [{ team: "mia", image: require("../assets/images/nba-players/mia/alec_burks.png") }],
  "alex_antetokounmpo": [{ team: "mil", image: require("../assets/images/nba-players/mil/alex_antetokounmpo.png") }],
  "alex_caruso": [{ team: "okc", image: require("../assets/images/nba-players/okc/alex_caruso.png") }],
  "alex_ducas": [{ team: "okc", image: require("../assets/images/nba-players/okc/alex_ducas.png") }],
  "alex_len": [{ team: "sac", image: require("../assets/images/nba-players/sac/alex_len.png") }],
  "alex_sarr": [{ team: "was", image: require("../assets/images/nba-players/was/alex_sarr.png") }],
  "alijah_martin": [{ team: "tor", image: require("../assets/images/nba-players/tor/alijah_martin.png") }],
  "alondes_williams": [{ team: "lac", image: require("../assets/images/nba-players/lac/alondes_williams.png") }],
  "alperen_sengun": [{ team: "hou", image: require("../assets/images/nba-players/hou/alperen_sengun.png") }],
  "amari_bailey": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/amari_bailey.png") }],
  "amari_williams": [{ team: "bos", image: require("../assets/images/nba-players/bos/amari_williams.png") }],
  "amen_thompson": [{ team: "hou", image: require("../assets/images/nba-players/hou/amen_thompson.png") }],
  "amir_coffey": [{ team: "lac", image: require("../assets/images/nba-players/lac/amir_coffey.png") }, { team: "mil", image: require("../assets/images/nba-players/mil/amir_coffey.png") }],
  "andre_drummond": [{ team: "phi", image: require("../assets/images/nba-players/phi/andre_drummond.png") }],
  "andre_jackson_jr": [{ team: "mil", image: require("../assets/images/nba-players/mil/andre_jackson_jr.png") }],
  "andre_jr__jackson": [{ team: "mil", image: require("../assets/images/nba-players/mil/andre_jr__jackson.png") }],
  "andrew_nembhard": [{ team: "ind", image: require("../assets/images/nba-players/ind/andrew_nembhard.png") }],
  "andrew_wiggins": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/andrew_wiggins.png") }, { team: "mia", image: require("../assets/images/nba-players/mia/andrew_wiggins.png") }],
  "anfernee_simons": [{ team: "bos", image: require("../assets/images/nba-players/bos/anfernee_simons.png") }, { team: "por", image: require("../assets/images/nba-players/por/anfernee_simons.png") }],
  "anthony_black": [{ team: "orl", image: require("../assets/images/nba-players/orl/anthony_black.png") }],
  "anthony_davis": [{ team: "dal", image: require("../assets/images/nba-players/dal/anthony_davis.png") }, { team: "lal", image: require("../assets/images/nba-players/lal/anthony_davis.png") }],
  "anthony_edwards": [{ team: "min", image: require("../assets/images/nba-players/min/anthony_edwards.png") }],
  "anthony_gill": [{ team: "was", image: require("../assets/images/nba-players/was/anthony_gill.png") }],
  "anton_watson": [{ team: "bos", image: require("../assets/images/nba-players/bos/anton_watson.png") }],
  "antonio_reeves": [{ team: "cha", image: require("../assets/images/nba-players/cha/antonio_reeves.png") }, { team: "nop", image: require("../assets/images/nba-players/nop/antonio_reeves.png") }],
  "anzejs_pasecniks": [{ team: "mil", image: require("../assets/images/nba-players/mil/anzejs_pasecniks.png") }],
  "ariel_hukporti": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/ariel_hukporti.png") }],
  "armando_bacot": [{ team: "mem", image: require("../assets/images/nba-players/mem/armando_bacot.png") }],
  "armel_traore": [{ team: "lal", image: require("../assets/images/nba-players/lal/armel_traore.png") }],
  "ausar_thompson": [{ team: "det", image: require("../assets/images/nba-players/det/ausar_thompson.png") }],
  "austin_reaves": [{ team: "lal", image: require("../assets/images/nba-players/lal/austin_reaves.png") }],
  "ayo_dosunmu": [{ team: "chi", image: require("../assets/images/nba-players/chi/ayo_dosunmu.png") }],
  "b__hinson": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/b__hinson.png") }],
  "bam_adebayo": [{ team: "mia", image: require("../assets/images/nba-players/mia/bam_adebayo.png") }],
  "baylor_scheierman": [{ team: "bos", image: require("../assets/images/nba-players/bos/baylor_scheierman.png") }],
  "ben_saraf": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/ben_saraf.png") }],
  "ben_sheppard": [{ team: "ind", image: require("../assets/images/nba-players/ind/ben_sheppard.png") }],
  "ben_simmons": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/ben_simmons.png") }],
  "bennedict_mathurin": [{ team: "ind", image: require("../assets/images/nba-players/ind/bennedict_mathurin.png") }],
  "bilal_coulibaly": [{ team: "was", image: require("../assets/images/nba-players/was/bilal_coulibaly.png") }],
  "bismack_biyombo": [{ team: "sas", image: require("../assets/images/nba-players/sas/bismack_biyombo.png") }],
  "blake_wesley": [{ team: "por", image: require("../assets/images/nba-players/por/blake_wesley.png") }, { team: "sas", image: require("../assets/images/nba-players/sas/blake_wesley.png") }],
  "bobby_portis": [{ team: "mil", image: require("../assets/images/nba-players/mil/bobby_portis.png") }],
  "bobi_klintman": [{ team: "det", image: require("../assets/images/nba-players/det/bobi_klintman.png") }],
  "bogdan_bogdanovi_": [{ team: "lac", image: require("../assets/images/nba-players/lac/bogdan_bogdanovi_.png") }],
  "bol_bol": [{ team: "phx", image: require("../assets/images/nba-players/phx/bol_bol.png") }],
  "bones_hyland": [{ team: "lac", image: require("../assets/images/nba-players/lac/bones_hyland.png") }, { team: "min", image: require("../assets/images/nba-players/min/bones_hyland.png") }],
  "boogie_ellis": [{ team: "sac", image: require("../assets/images/nba-players/sac/boogie_ellis.png") }],
  "bradley_beal": [{ team: "lac", image: require("../assets/images/nba-players/lac/bradley_beal.png") }, { team: "phx", image: require("../assets/images/nba-players/phx/bradley_beal.png") }],
  "branden_carlson": [{ team: "okc", image: require("../assets/images/nba-players/okc/branden_carlson.png") }, { team: "tor", image: require("../assets/images/nba-players/tor/branden_carlson.png") }],
  "brandin_podziemski": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/brandin_podziemski.png") }],
  "brandon_boston_jr_": [{ team: "sas", image: require("../assets/images/nba-players/sas/brandon_boston_jr_.png") }],
  "brandon_clarke": [{ team: "mem", image: require("../assets/images/nba-players/mem/brandon_clarke.png") }],
  "brandon_ingram": [{ team: "nop", image: require("../assets/images/nba-players/nop/brandon_ingram.png") }, { team: "tor", image: require("../assets/images/nba-players/tor/brandon_ingram.png") }],
  "brandon_miller": [{ team: "cha", image: require("../assets/images/nba-players/cha/brandon_miller.png") }],
  "brandon_williams": [{ team: "dal", image: require("../assets/images/nba-players/dal/brandon_williams.png") }],
  "braxton_key": [{ team: "lac", image: require("../assets/images/nba-players/lac/braxton_key.png") }],
  "brice_sensabaugh": [{ team: "uta", image: require("../assets/images/nba-players/uta/brice_sensabaugh.png") }],
  "brodric_thomas": [{ team: "sac", image: require("../assets/images/nba-players/sac/brodric_thomas.png") }],
  "bronny_james": [{ team: "lal", image: require("../assets/images/nba-players/lal/bronny_james.png") }],
  "brook_lopez": [{ team: "lac", image: require("../assets/images/nba-players/lac/brook_lopez.png") }, { team: "mil", image: require("../assets/images/nba-players/mil/brook_lopez.png") }],
  "brooks_barnhizer": [{ team: "okc", image: require("../assets/images/nba-players/okc/brooks_barnhizer.png") }],
  "bruce_brown": [{ team: "den", image: require("../assets/images/nba-players/den/bruce_brown.png") }],
  "bruno_fernando": [{ team: "tor", image: require("../assets/images/nba-players/tor/bruno_fernando.png") }],
  "bryce_mcgowens": [{ team: "nop", image: require("../assets/images/nba-players/nop/bryce_mcgowens.png") }, { team: "por", image: require("../assets/images/nba-players/por/bryce_mcgowens.png") }],
  "bub_carrington": [{ team: "was", image: require("../assets/images/nba-players/was/bub_carrington.png") }],
  "buddy_hield": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/buddy_hield.png") }],
  "cade_cunningham": [{ team: "det", image: require("../assets/images/nba-players/det/cade_cunningham.png") }],
  "caleb_daniels": [{ team: "mia", image: require("../assets/images/nba-players/mia/caleb_daniels.png") }],
  "caleb_houstan": [{ team: "orl", image: require("../assets/images/nba-players/orl/caleb_houstan.png") }],
  "caleb_love": [{ team: "por", image: require("../assets/images/nba-players/por/caleb_love.png") }],
  "caleb_martin": [{ team: "dal", image: require("../assets/images/nba-players/dal/caleb_martin.png") }, { team: "phi", image: require("../assets/images/nba-players/phi/caleb_martin.png") }],
  "cam_christie": [{ team: "lac", image: require("../assets/images/nba-players/lac/cam_christie.png") }],
  "cam_reddish": [{ team: "lal", image: require("../assets/images/nba-players/lal/cam_reddish.png") }],
  "cam_spencer": [{ team: "mem", image: require("../assets/images/nba-players/mem/cam_spencer.png") }],
  "cam_thomas": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/cam_thomas.png") }],
  "cam_whitmore": [{ team: "hou", image: require("../assets/images/nba-players/hou/cam_whitmore.png") }, { team: "was", image: require("../assets/images/nba-players/was/cam_whitmore.png") }],
  "cameron_johnson": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/cameron_johnson.png") }, { team: "den", image: require("../assets/images/nba-players/den/cameron_johnson.png") }],
  "cameron_payne": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/cameron_payne.png") }],
  "caris_levert": [{ team: "cle", image: require("../assets/images/nba-players/cle/caris_levert.png") }, { team: "det", image: require("../assets/images/nba-players/det/caris_levert.png") }],
  "carter_bryant": [{ team: "sas", image: require("../assets/images/nba-players/sas/carter_bryant.png") }],
  "cason_wallace": [{ team: "okc", image: require("../assets/images/nba-players/okc/cason_wallace.png") }],
  "cedric_coward": [{ team: "mem", image: require("../assets/images/nba-players/mem/cedric_coward.png") }],
  "chaney_johnson": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/chaney_johnson.png") }],
  "charles_bassey": [{ team: "sas", image: require("../assets/images/nba-players/sas/charles_bassey.png") }],
  "charles_bediako": [{ team: "den", image: require("../assets/images/nba-players/den/charles_bediako.png") }],
  "charlie_brown_jr_": [{ team: "cha", image: require("../assets/images/nba-players/cha/charlie_brown_jr_.png") }],
  "chaz_lanier": [{ team: "det", image: require("../assets/images/nba-players/det/chaz_lanier.png") }],
  "chet_holmgren": [{ team: "okc", image: require("../assets/images/nba-players/okc/chet_holmgren.png") }],
  "chris_boucher": [{ team: "bos", image: require("../assets/images/nba-players/bos/chris_boucher.png") }, { team: "tor", image: require("../assets/images/nba-players/tor/chris_boucher.png") }],
  "chris_duarte": [{ team: "chi", image: require("../assets/images/nba-players/chi/chris_duarte.png") }],
  "chris_livingston": [{ team: "cle", image: require("../assets/images/nba-players/cle/chris_livingston.png") }, { team: "mil", image: require("../assets/images/nba-players/mil/chris_livingston.png") }],
  "chris_mason": [{ team: "lal", image: require("../assets/images/nba-players/lal/chris_mason.png") }],
  "chris_paul": [{ team: "lac", image: require("../assets/images/nba-players/lac/chris_paul.png") }, { team: "sas", image: require("../assets/images/nba-players/sas/chris_paul.png") }],
  "chris_youngblood": [{ team: "okc", image: require("../assets/images/nba-players/okc/chris_youngblood.png") }],
  "christian_braun": [{ team: "den", image: require("../assets/images/nba-players/den/christian_braun.png") }],
  "christian_koloko": [{ team: "lal", image: require("../assets/images/nba-players/lal/christian_koloko.png") }],
  "chucky_hepburn": [{ team: "tor", image: require("../assets/images/nba-players/tor/chucky_hepburn.png") }],
  "chuma_okeke": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/chuma_okeke.png") }],
  "cj_mccollum": [{ team: "nop", image: require("../assets/images/nba-players/nop/cj_mccollum.png") }],
  "clint_capela": [{ team: "hou", image: require("../assets/images/nba-players/hou/clint_capela.png") }],
  "coby_white": [{ team: "chi", image: require("../assets/images/nba-players/chi/coby_white.png") }],
  "cody_martin": [{ team: "cha", image: require("../assets/images/nba-players/cha/cody_martin.png") }],
  "cody_williams": [{ team: "uta", image: require("../assets/images/nba-players/uta/cody_williams.png") }],
  "colby_jones": [{ team: "sac", image: require("../assets/images/nba-players/sac/colby_jones.png") }],
  "cole_anthony": [{ team: "mil", image: require("../assets/images/nba-players/mil/cole_anthony.png") }, { team: "orl", image: require("../assets/images/nba-players/orl/cole_anthony.png") }],
  "cole_swider": [{ team: "det", image: require("../assets/images/nba-players/det/cole_swider.png") }, { team: "ind", image: require("../assets/images/nba-players/ind/cole_swider.png") }],
  "colin_castleton": [{ team: "lal", image: require("../assets/images/nba-players/lal/colin_castleton.png") }, { team: "mem", image: require("../assets/images/nba-players/mem/colin_castleton.png") }, { team: "orl", image: require("../assets/images/nba-players/orl/colin_castleton.png") }],
  "collin_gillespie": [{ team: "phx", image: require("../assets/images/nba-players/phx/collin_gillespie.png") }],
  "collin_murray_boyles": [{ team: "tor", image: require("../assets/images/nba-players/tor/collin_murray_boyles.png") }],
  "collin_sexton": [{ team: "cha", image: require("../assets/images/nba-players/cha/collin_sexton.png") }, { team: "uta", image: require("../assets/images/nba-players/uta/collin_sexton.png") }],
  "cooper_flagg": [{ team: "dal", image: require("../assets/images/nba-players/dal/cooper_flagg.png") }],
  "corey_kispert": [{ team: "was", image: require("../assets/images/nba-players/was/corey_kispert.png") }],
  "cormac_ryan": [{ team: "okc", image: require("../assets/images/nba-players/okc/cormac_ryan.png") }],
  "cory_joseph": [{ team: "orl", image: require("../assets/images/nba-players/orl/cory_joseph.png") }],
  "craig_jr__porter": [{ team: "cle", image: require("../assets/images/nba-players/cle/craig_jr__porter.png") }],
  "craig_porter_jr": [{ team: "cle", image: require("../assets/images/nba-players/cle/craig_porter_jr.png") }],
  "curtis_jones": [{ team: "den", image: require("../assets/images/nba-players/den/curtis_jones.png") }],
  "d__skapintsev": [{ team: "bos", image: require("../assets/images/nba-players/bos/d__skapintsev.png") }],
  "d_angelo_russell": [{ team: "lal", image: require("../assets/images/nba-players/lal/d_angelo_russell.png") }],
  "d_j__carton": [{ team: "tor", image: require("../assets/images/nba-players/tor/d_j__carton.png") }],
  "daeqwon_plowden": [{ team: "sac", image: require("../assets/images/nba-players/sac/daeqwon_plowden.png") }],
  "daishen_nix": [{ team: "min", image: require("../assets/images/nba-players/min/daishen_nix.png") }],
  "dalano_banton": [{ team: "por", image: require("../assets/images/nba-players/por/dalano_banton.png") }],
  "dalen_terry": [{ team: "chi", image: require("../assets/images/nba-players/chi/dalen_terry.png") }],
  "dalton_knecht": [{ team: "lal", image: require("../assets/images/nba-players/lal/dalton_knecht.png") }],
  "damian_lillard": [{ team: "mil", image: require("../assets/images/nba-players/mil/damian_lillard.png") }, { team: "por", image: require("../assets/images/nba-players/por/damian_lillard.png") }],
  "damion_lee": [{ team: "phx", image: require("../assets/images/nba-players/phx/damion_lee.png") }],
  "dangelo_russell": [{ team: "dal", image: require("../assets/images/nba-players/dal/dangelo_russell.png") }],
  "daniel_gafford": [{ team: "dal", image: require("../assets/images/nba-players/dal/daniel_gafford.png") }],
  "daniel_theis": [{ team: "nop", image: require("../assets/images/nba-players/nop/daniel_theis.png") }],
  "daniss_jenkins": [{ team: "det", image: require("../assets/images/nba-players/det/daniss_jenkins.png") }],
  "danny_wolf": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/danny_wolf.png") }],
  "dante_exum": [{ team: "dal", image: require("../assets/images/nba-players/dal/dante_exum.png") }],
  "daquan_jeffries": [{ team: "cha", image: require("../assets/images/nba-players/cha/daquan_jeffries.png") }],
  "dario_saric": [{ team: "den", image: require("../assets/images/nba-players/den/dario_saric.png") }, { team: "sac", image: require("../assets/images/nba-players/sac/dario_saric.png") }],
  "dariq_whitehead": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/dariq_whitehead.png") }],
  "darius_garland": [{ team: "cle", image: require("../assets/images/nba-players/cle/darius_garland.png") }],
  "daron_holmes_ii": [{ team: "den", image: require("../assets/images/nba-players/den/daron_holmes_ii.png") }],
  "david_duke_jr_": [{ team: "sas", image: require("../assets/images/nba-players/sas/david_duke_jr_.png") }],
  "david_jones_garcia": [{ team: "sas", image: require("../assets/images/nba-players/sas/david_jones_garcia.png") }],
  "davion_mitchell": [{ team: "mia", image: require("../assets/images/nba-players/mia/davion_mitchell.png") }, { team: "tor", image: require("../assets/images/nba-players/tor/davion_mitchell.png") }],
  "day_ron_sharpe": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/day_ron_sharpe.png") }],
  "dayron_sharpe": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/dayron_sharpe.png") }],
  "de_aaron_fox": [{ team: "sac", image: require("../assets/images/nba-players/sac/de_aaron_fox.png") }],
  "de_anthony_melton": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/de_anthony_melton.png") }],
  "deaaron_fox": [{ team: "sas", image: require("../assets/images/nba-players/sas/deaaron_fox.png") }],
  "dean_wade": [{ team: "cle", image: require("../assets/images/nba-players/cle/dean_wade.png") }],
  "deandre_ayton": [{ team: "lal", image: require("../assets/images/nba-players/lal/deandre_ayton.png") }, { team: "por", image: require("../assets/images/nba-players/por/deandre_ayton.png") }],
  "deandre_hunter": [{ team: "cle", image: require("../assets/images/nba-players/cle/deandre_hunter.png") }],
  "deandre_jordan": [{ team: "den", image: require("../assets/images/nba-players/den/deandre_jordan.png") }, { team: "nop", image: require("../assets/images/nba-players/nop/deandre_jordan.png") }],
  "deanthony_melton": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/deanthony_melton.png") }],
  "dejounte_murray": [{ team: "nop", image: require("../assets/images/nba-players/nop/dejounte_murray.png") }],
  "delon_wright": [{ team: "mil", image: require("../assets/images/nba-players/mil/delon_wright.png") }, { team: "nyk", image: require("../assets/images/nba-players/nyk/delon_wright.png") }],
  "demar_derozan": [{ team: "sac", image: require("../assets/images/nba-players/sac/demar_derozan.png") }],
  "deni_avdija": [{ team: "por", image: require("../assets/images/nba-players/por/deni_avdija.png") }],
  "dennis_schr_der": [{ team: "sac", image: require("../assets/images/nba-players/sac/dennis_schr_der.png") }],
  "dennis_schroder": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/dennis_schroder.png") }],
  "dereck_ii_lively": [{ team: "dal", image: require("../assets/images/nba-players/dal/dereck_ii_lively.png") }],
  "dereck_lively_ii": [{ team: "dal", image: require("../assets/images/nba-players/dal/dereck_lively_ii.png") }],
  "derik_queen": [{ team: "nop", image: require("../assets/images/nba-players/nop/derik_queen.png") }],
  "derrick_jones_jr": [{ team: "lac", image: require("../assets/images/nba-players/lac/derrick_jones_jr.png") }],
  "derrick_jones_jr_": [{ team: "lac", image: require("../assets/images/nba-players/lac/derrick_jones_jr_.png") }],
  "derrick_white": [{ team: "bos", image: require("../assets/images/nba-players/bos/derrick_white.png") }],
  "desmond_bane": [{ team: "mem", image: require("../assets/images/nba-players/mem/desmond_bane.png") }, { team: "orl", image: require("../assets/images/nba-players/orl/desmond_bane.png") }],
  "devin_booker": [{ team: "phx", image: require("../assets/images/nba-players/phx/devin_booker.png") }],
  "devin_carter": [{ team: "sac", image: require("../assets/images/nba-players/sac/devin_carter.png") }],
  "devin_vassell": [{ team: "sas", image: require("../assets/images/nba-players/sas/devin_vassell.png") }],
  "devonte__graham": [{ team: "por", image: require("../assets/images/nba-players/por/devonte__graham.png") }],
  "dillon_brooks": [{ team: "hou", image: require("../assets/images/nba-players/hou/dillon_brooks.png") }, { team: "phx", image: require("../assets/images/nba-players/phx/dillon_brooks.png") }],
  "dillon_jones": [{ team: "okc", image: require("../assets/images/nba-players/okc/dillon_jones.png") }],
  "dj_steward": [{ team: "chi", image: require("../assets/images/nba-players/chi/dj_steward.png") }],
  "domantas_sabonis": [{ team: "sac", image: require("../assets/images/nba-players/sac/domantas_sabonis.png") }],
  "dominick_barlow": [{ team: "phi", image: require("../assets/images/nba-players/phi/dominick_barlow.png") }],
  "donovan_clingan": [{ team: "por", image: require("../assets/images/nba-players/por/donovan_clingan.png") }],
  "donovan_mitchell": [{ team: "cle", image: require("../assets/images/nba-players/cle/donovan_mitchell.png") }],
  "donte_divincenzo": [{ team: "min", image: require("../assets/images/nba-players/min/donte_divincenzo.png") }],
  "dorian_finney_smith": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/dorian_finney_smith.png") }, { team: "hou", image: require("../assets/images/nba-players/hou/dorian_finney_smith.png") }, { team: "lal", image: require("../assets/images/nba-players/lal/dorian_finney_smith.png") }],
  "doug_mcdermott": [{ team: "sac", image: require("../assets/images/nba-players/sac/doug_mcdermott.png") }],
  "drake_powell": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/drake_powell.png") }],
  "draymond_green": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/draymond_green.png") }],
  "drew_eubanks": [{ team: "sac", image: require("../assets/images/nba-players/sac/drew_eubanks.png") }, { team: "uta", image: require("../assets/images/nba-players/uta/drew_eubanks.png") }],
  "drew_peterson": [{ team: "bos", image: require("../assets/images/nba-players/bos/drew_peterson.png") }],
  "drew_timme": [{ team: "lal", image: require("../assets/images/nba-players/lal/drew_timme.png") }],
  "dru_smith": [{ team: "mia", image: require("../assets/images/nba-players/mia/dru_smith.png") }],
  "duane_washington_jr_": [{ team: "cha", image: require("../assets/images/nba-players/cha/duane_washington_jr_.png") }],
  "duncan_robinson": [{ team: "det", image: require("../assets/images/nba-players/det/duncan_robinson.png") }, { team: "mia", image: require("../assets/images/nba-players/mia/duncan_robinson.png") }],
  "duop_reath": [{ team: "por", image: require("../assets/images/nba-players/por/duop_reath.png") }],
  "dwight_powell": [{ team: "dal", image: require("../assets/images/nba-players/dal/dwight_powell.png") }],
  "dylan_cardwell": [{ team: "sac", image: require("../assets/images/nba-players/sac/dylan_cardwell.png") }],
  "dylan_harper": [{ team: "sas", image: require("../assets/images/nba-players/sas/dylan_harper.png") }],
  "e__harkless": [{ team: "lac", image: require("../assets/images/nba-players/lac/e__harkless.png") }],
  "e_j__liddell": [{ team: "chi", image: require("../assets/images/nba-players/chi/e_j__liddell.png") }],
  "egor_demin": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/egor_demin.png") }],
  "ej_harkless": [{ team: "lac", image: require("../assets/images/nba-players/lac/ej_harkless.png") }, { team: "uta", image: require("../assets/images/nba-players/uta/ej_harkless.png") }],
  "ej_liddell": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/ej_liddell.png") }],
  "elfrid_payton": [{ team: "nop", image: require("../assets/images/nba-players/nop/elfrid_payton.png") }],
  "elijah_harkless": [{ team: "uta", image: require("../assets/images/nba-players/uta/elijah_harkless.png") }],
  "emanuel_miller": [{ team: "chi", image: require("../assets/images/nba-players/chi/emanuel_miller.png") }, { team: "dal", image: require("../assets/images/nba-players/dal/emanuel_miller.png") }],
  "enrique_freeman": [{ team: "ind", image: require("../assets/images/nba-players/ind/enrique_freeman.png") }, { team: "min", image: require("../assets/images/nba-players/min/enrique_freeman.png") }],
  "eric_gordon": [{ team: "phi", image: require("../assets/images/nba-players/phi/eric_gordon.png") }],
  "ethan_thompson": [{ team: "ind", image: require("../assets/images/nba-players/ind/ethan_thompson.png") }, { team: "orl", image: require("../assets/images/nba-players/orl/ethan_thompson.png") }],
  "eugene_omoruyi": [{ team: "min", image: require("../assets/images/nba-players/min/eugene_omoruyi.png") }],
  "evan_mobley": [{ team: "cle", image: require("../assets/images/nba-players/cle/evan_mobley.png") }],
  "frank_kaminsky": [{ team: "phx", image: require("../assets/images/nba-players/phx/frank_kaminsky.png") }],
  "franz_wagner": [{ team: "orl", image: require("../assets/images/nba-players/orl/franz_wagner.png") }],
  "fred_vanvleet": [{ team: "hou", image: require("../assets/images/nba-players/hou/fred_vanvleet.png") }],
  "gabe_mcglothan": [{ team: "den", image: require("../assets/images/nba-players/den/gabe_mcglothan.png") }],
  "gabe_vincent": [{ team: "lal", image: require("../assets/images/nba-players/lal/gabe_vincent.png") }],
  "garrett_temple": [{ team: "tor", image: require("../assets/images/nba-players/tor/garrett_temple.png") }],
  "gary_harris": [{ team: "mil", image: require("../assets/images/nba-players/mil/gary_harris.png") }, { team: "orl", image: require("../assets/images/nba-players/orl/gary_harris.png") }],
  "gary_payton_ii": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/gary_payton_ii.png") }],
  "gary_trent_jr": [{ team: "mil", image: require("../assets/images/nba-players/mil/gary_trent_jr.png") }],
  "gary_trent_jr_": [{ team: "mil", image: require("../assets/images/nba-players/mil/gary_trent_jr_.png") }],
  "georges_niang": [{ team: "cle", image: require("../assets/images/nba-players/cle/georges_niang.png") }, { team: "uta", image: require("../assets/images/nba-players/uta/georges_niang.png") }],
  "gg_jackson": [{ team: "mem", image: require("../assets/images/nba-players/mem/gg_jackson.png") }],
  "giannis_antetokounmpo": [{ team: "mil", image: require("../assets/images/nba-players/mil/giannis_antetokounmpo.png") }],
  "goga_bitadze": [{ team: "orl", image: require("../assets/images/nba-players/orl/goga_bitadze.png") }],
  "gradey_dick": [{ team: "tor", image: require("../assets/images/nba-players/tor/gradey_dick.png") }],
  "grant_williams": [{ team: "cha", image: require("../assets/images/nba-players/cha/grant_williams.png") }],
  "grayson_allen": [{ team: "phx", image: require("../assets/images/nba-players/phx/grayson_allen.png") }],
  "guerschon_yabusele": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/guerschon_yabusele.png") }, { team: "phi", image: require("../assets/images/nba-players/phi/guerschon_yabusele.png") }],
  "gui_santos": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/gui_santos.png") }],
  "harrison_barnes": [{ team: "sas", image: require("../assets/images/nba-players/sas/harrison_barnes.png") }],
  "harrison_ingram": [{ team: "sas", image: require("../assets/images/nba-players/sas/harrison_ingram.png") }],
  "harry_iii_giles": [{ team: "cha", image: require("../assets/images/nba-players/cha/harry_iii_giles.png") }],
  "haywood_highsmith": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/haywood_highsmith.png") }, { team: "mia", image: require("../assets/images/nba-players/mia/haywood_highsmith.png") }],
  "herbert_jones": [{ team: "nop", image: require("../assets/images/nba-players/nop/herbert_jones.png") }],
  "hugo_gonz_lez": [{ team: "bos", image: require("../assets/images/nba-players/bos/hugo_gonz_lez.png") }],
  "hunter_dickinson": [{ team: "nop", image: require("../assets/images/nba-players/nop/hunter_dickinson.png") }],
  "hunter_tyson": [{ team: "den", image: require("../assets/images/nba-players/den/hunter_tyson.png") }],
  "immanuel_quickley": [{ team: "tor", image: require("../assets/images/nba-players/tor/immanuel_quickley.png") }],
  "isaac_jones": [{ team: "det", image: require("../assets/images/nba-players/det/isaac_jones.png") }, { team: "sac", image: require("../assets/images/nba-players/sac/isaac_jones.png") }],
  "isaac_okoro": [{ team: "chi", image: require("../assets/images/nba-players/chi/isaac_okoro.png") }, { team: "cle", image: require("../assets/images/nba-players/cle/isaac_okoro.png") }],
  "isaiah_collier": [{ team: "uta", image: require("../assets/images/nba-players/uta/isaiah_collier.png") }],
  "isaiah_crawford": [{ team: "hou", image: require("../assets/images/nba-players/hou/isaiah_crawford.png") }, { team: "sac", image: require("../assets/images/nba-players/sac/isaiah_crawford.png") }],
  "isaiah_hartenstein": [{ team: "okc", image: require("../assets/images/nba-players/okc/isaiah_hartenstein.png") }],
  "isaiah_jackson": [{ team: "ind", image: require("../assets/images/nba-players/ind/isaiah_jackson.png") }],
  "isaiah_joe": [{ team: "okc", image: require("../assets/images/nba-players/okc/isaiah_joe.png") }],
  "isaiah_livers": [{ team: "phx", image: require("../assets/images/nba-players/phx/isaiah_livers.png") }],
  "isaiah_mobley": [{ team: "phi", image: require("../assets/images/nba-players/phi/isaiah_mobley.png") }],
  "isaiah_stevens": [{ team: "mia", image: require("../assets/images/nba-players/mia/isaiah_stevens.png") }, { team: "sac", image: require("../assets/images/nba-players/sac/isaiah_stevens.png") }],
  "isaiah_stewart": [{ team: "det", image: require("../assets/images/nba-players/det/isaiah_stewart.png") }],
  "ivica_zubac": [{ team: "lac", image: require("../assets/images/nba-players/lac/ivica_zubac.png") }],
  "j_oduro": [{ team: "nop", image: require("../assets/images/nba-players/nop/j_oduro.png") }],
  "ja_kobe_walter": [{ team: "tor", image: require("../assets/images/nba-players/tor/ja_kobe_walter.png") }],
  "ja_morant": [{ team: "mem", image: require("../assets/images/nba-players/mem/ja_morant.png") }],
  "jabari_smith_jr": [{ team: "hou", image: require("../assets/images/nba-players/hou/jabari_smith_jr.png") }],
  "jabari_smith_jr_": [{ team: "hou", image: require("../assets/images/nba-players/hou/jabari_smith_jr_.png") }],
  "jabari_walker": [{ team: "phi", image: require("../assets/images/nba-players/phi/jabari_walker.png") }, { team: "por", image: require("../assets/images/nba-players/por/jabari_walker.png") }],
  "jack_mcveigh": [{ team: "hou", image: require("../assets/images/nba-players/hou/jack_mcveigh.png") }],
  "jackson_rowe": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/jackson_rowe.png") }],
  "jacob_gilyard": [{ team: "cle", image: require("../assets/images/nba-players/cle/jacob_gilyard.png") }],
  "jacob_toppin": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/jacob_toppin.png") }],
  "jaden_hardy": [{ team: "dal", image: require("../assets/images/nba-players/dal/jaden_hardy.png") }],
  "jaden_ivey": [{ team: "det", image: require("../assets/images/nba-players/det/jaden_ivey.png") }],
  "jaden_mcdaniels": [{ team: "min", image: require("../assets/images/nba-players/min/jaden_mcdaniels.png") }],
  "jaden_springer": [{ team: "bos", image: require("../assets/images/nba-players/bos/jaden_springer.png") }],
  "jae_sean_tate": [{ team: "hou", image: require("../assets/images/nba-players/hou/jae_sean_tate.png") }],
  "jaesean_tate": [{ team: "hou", image: require("../assets/images/nba-players/hou/jaesean_tate.png") }],
  "jahmai_mashack": [{ team: "mem", image: require("../assets/images/nba-players/mem/jahmai_mashack.png") }],
  "jahmi_us_ramsey": [{ team: "tor", image: require("../assets/images/nba-players/tor/jahmi_us_ramsey.png") }],
  "jahmir_young": [{ team: "den", image: require("../assets/images/nba-players/den/jahmir_young.png") }, { team: "mia", image: require("../assets/images/nba-players/mia/jahmir_young.png") }],
  "jaime_jaquez_jr": [{ team: "mia", image: require("../assets/images/nba-players/mia/jaime_jaquez_jr.png") }],
  "jake_laravia": [{ team: "lal", image: require("../assets/images/nba-players/lal/jake_laravia.png") }, { team: "mem", image: require("../assets/images/nba-players/mem/jake_laravia.png") }],
  "jakob_poeltl": [{ team: "tor", image: require("../assets/images/nba-players/tor/jakob_poeltl.png") }],
  "jakobe_walter": [{ team: "tor", image: require("../assets/images/nba-players/tor/jakobe_walter.png") }],
  "jalen_bridges": [{ team: "phx", image: require("../assets/images/nba-players/phx/jalen_bridges.png") }],
  "jalen_brunson": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/jalen_brunson.png") }],
  "jalen_crutcher": [{ team: "nop", image: require("../assets/images/nba-players/nop/jalen_crutcher.png") }],
  "jalen_duren": [{ team: "det", image: require("../assets/images/nba-players/det/jalen_duren.png") }],
  "jalen_green": [{ team: "hou", image: require("../assets/images/nba-players/hou/jalen_green.png") }, { team: "phx", image: require("../assets/images/nba-players/phx/jalen_green.png") }],
  "jalen_hoodschifino": [{ team: "lal", image: require("../assets/images/nba-players/lal/jalen_hoodschifino.png") }, { team: "uta", image: require("../assets/images/nba-players/uta/jalen_hoodschifino.png") }],
  "jalen_mcdaniels": [{ team: "sac", image: require("../assets/images/nba-players/sac/jalen_mcdaniels.png") }],
  "jalen_pickett": [{ team: "den", image: require("../assets/images/nba-players/den/jalen_pickett.png") }],
  "jalen_slawson": [{ team: "orl", image: require("../assets/images/nba-players/orl/jalen_slawson.png") }],
  "jalen_smith": [{ team: "chi", image: require("../assets/images/nba-players/chi/jalen_smith.png") }],
  "jalen_suggs": [{ team: "orl", image: require("../assets/images/nba-players/orl/jalen_suggs.png") }],
  "jalen_williams": [{ team: "okc", image: require("../assets/images/nba-players/okc/jalen_williams.png") }],
  "jalen_wilson": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/jalen_wilson.png") }],
  "jamal_cain": [{ team: "nop", image: require("../assets/images/nba-players/nop/jamal_cain.png") }, { team: "orl", image: require("../assets/images/nba-players/orl/jamal_cain.png") }],
  "jamal_murray": [{ team: "den", image: require("../assets/images/nba-players/den/jamal_murray.png") }],
  "jamal_shead": [{ team: "tor", image: require("../assets/images/nba-players/tor/jamal_shead.png") }],
  "jamaree_bouyea": [{ team: "phx", image: require("../assets/images/nba-players/phx/jamaree_bouyea.png") }],
  "jamarion_sharp": [{ team: "dal", image: require("../assets/images/nba-players/dal/jamarion_sharp.png") }],
  "james_akinjo": [{ team: "mil", image: require("../assets/images/nba-players/mil/james_akinjo.png") }],
  "james_harden": [{ team: "lac", image: require("../assets/images/nba-players/lac/james_harden.png") }],
  "james_johnson": [{ team: "ind", image: require("../assets/images/nba-players/ind/james_johnson.png") }],
  "james_wiseman": [{ team: "ind", image: require("../assets/images/nba-players/ind/james_wiseman.png") }],
  "jamie_jr__jaquez": [{ team: "mia", image: require("../assets/images/nba-players/mia/jamie_jr__jaquez.png") }],
  "jamir_watkins": [{ team: "was", image: require("../assets/images/nba-players/was/jamir_watkins.png") }],
  "jamison_battle": [{ team: "tor", image: require("../assets/images/nba-players/tor/jamison_battle.png") }],
  "jarace_walker": [{ team: "ind", image: require("../assets/images/nba-players/ind/jarace_walker.png") }],
  "jared_butler": [{ team: "was", image: require("../assets/images/nba-players/was/jared_butler.png") }],
  "jared_mccain": [{ team: "phi", image: require("../assets/images/nba-players/phi/jared_mccain.png") }],
  "jared_rhoden": [{ team: "tor", image: require("../assets/images/nba-players/tor/jared_rhoden.png") }],
  "jaren_jackson_jr": [{ team: "mem", image: require("../assets/images/nba-players/mem/jaren_jackson_jr.png") }],
  "jaren_jackson_jr_": [{ team: "mem", image: require("../assets/images/nba-players/mem/jaren_jackson_jr_.png") }],
  "jarred_vanderbilt": [{ team: "lal", image: require("../assets/images/nba-players/lal/jarred_vanderbilt.png") }],
  "jarrett_allen": [{ team: "cle", image: require("../assets/images/nba-players/cle/jarrett_allen.png") }],
  "jarrett_culver": [{ team: "orl", image: require("../assets/images/nba-players/orl/jarrett_culver.png") }],
  "jase_richardson": [{ team: "orl", image: require("../assets/images/nba-players/orl/jase_richardson.png") }],
  "jason_preston": [{ team: "uta", image: require("../assets/images/nba-players/uta/jason_preston.png") }],
  "javante_mccoy": [{ team: "det", image: require("../assets/images/nba-players/det/javante_mccoy.png") }],
  "javon_small": [{ team: "mem", image: require("../assets/images/nba-players/mem/javon_small.png") }],
  "javonte_cooke": [{ team: "por", image: require("../assets/images/nba-players/por/javonte_cooke.png") }],
  "javonte_green": [{ team: "det", image: require("../assets/images/nba-players/det/javonte_green.png") }, { team: "nop", image: require("../assets/images/nba-players/nop/javonte_green.png") }],
  "javonte_smart": [{ team: "orl", image: require("../assets/images/nba-players/orl/javonte_smart.png") }],
  "jaxson_hayes": [{ team: "lal", image: require("../assets/images/nba-players/lal/jaxson_hayes.png") }],
  "jay_huff": [{ team: "ind", image: require("../assets/images/nba-players/ind/jay_huff.png") }, { team: "mem", image: require("../assets/images/nba-players/mem/jay_huff.png") }],
  "jaylen_brown": [{ team: "bos", image: require("../assets/images/nba-players/bos/jaylen_brown.png") }],
  "jaylen_clark": [{ team: "min", image: require("../assets/images/nba-players/min/jaylen_clark.png") }],
  "jaylen_martin": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/jaylen_martin.png") }],
  "jaylen_nowell": [{ team: "was", image: require("../assets/images/nba-players/was/jaylen_nowell.png") }],
  "jaylen_wells": [{ team: "mem", image: require("../assets/images/nba-players/mem/jaylen_wells.png") }],
  "jaylin_williams": [{ team: "okc", image: require("../assets/images/nba-players/okc/jaylin_williams.png") }],
  "jaylon_tyson": [{ team: "cle", image: require("../assets/images/nba-players/cle/jaylon_tyson.png") }],
  "jayson_tatum": [{ team: "bos", image: require("../assets/images/nba-players/bos/jayson_tatum.png") }],
  "jazian_gortman": [{ team: "dal", image: require("../assets/images/nba-players/dal/jazian_gortman.png") }],
  "jd_davison": [{ team: "bos", image: require("../assets/images/nba-players/bos/jd_davison.png") }, { team: "hou", image: require("../assets/images/nba-players/hou/jd_davison.png") }],
  "jeenathan_williams": [{ team: "hou", image: require("../assets/images/nba-players/hou/jeenathan_williams.png") }],
  "jeff_dowtin": [{ team: "phi", image: require("../assets/images/nba-players/phi/jeff_dowtin.png") }],
  "jeff_green": [{ team: "hou", image: require("../assets/images/nba-players/hou/jeff_green.png") }],
  "jerami_grant": [{ team: "por", image: require("../assets/images/nba-players/por/jerami_grant.png") }],
  "jeremiah_fears": [{ team: "nop", image: require("../assets/images/nba-players/nop/jeremiah_fears.png") }],
  "jeremiah_robinson_earl": [{ team: "nop", image: require("../assets/images/nba-players/nop/jeremiah_robinson_earl.png") }],
  "jeremy_sochan": [{ team: "sas", image: require("../assets/images/nba-players/sas/jeremy_sochan.png") }],
  "jericho_sims": [{ team: "mil", image: require("../assets/images/nba-players/mil/jericho_sims.png") }, { team: "nyk", image: require("../assets/images/nba-players/nyk/jericho_sims.png") }],
  "jesse_edwards": [{ team: "min", image: require("../assets/images/nba-players/min/jesse_edwards.png") }],
  "jett_howard": [{ team: "orl", image: require("../assets/images/nba-players/orl/jett_howard.png") }],
  "jevon_carter": [{ team: "chi", image: require("../assets/images/nba-players/chi/jevon_carter.png") }],
  "jimmy_butler": [{ team: "mia", image: require("../assets/images/nba-players/mia/jimmy_butler.png") }],
  "jimmy_butler_iii": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/jimmy_butler_iii.png") }],
  "joan_beringer": [{ team: "min", image: require("../assets/images/nba-players/min/joan_beringer.png") }],
  "jock_landale": [{ team: "hou", image: require("../assets/images/nba-players/hou/jock_landale.png") }, { team: "mem", image: require("../assets/images/nba-players/mem/jock_landale.png") }],
  "joe_ingles": [{ team: "min", image: require("../assets/images/nba-players/min/joe_ingles.png") }],
  "joel_embiid": [{ team: "phi", image: require("../assets/images/nba-players/phi/joel_embiid.png") }],
  "john_collins": [{ team: "lac", image: require("../assets/images/nba-players/lac/john_collins.png") }, { team: "uta", image: require("../assets/images/nba-players/uta/john_collins.png") }],
  "john_konchar": [{ team: "mem", image: require("../assets/images/nba-players/mem/john_konchar.png") }],
  "john_tonje": [{ team: "uta", image: require("../assets/images/nba-players/uta/john_tonje.png") }],
  "johni_broome": [{ team: "phi", image: require("../assets/images/nba-players/phi/johni_broome.png") }],
  "johnny_davis": [{ team: "was", image: require("../assets/images/nba-players/was/johnny_davis.png") }],
  "johnny_furphy": [{ team: "ind", image: require("../assets/images/nba-players/ind/johnny_furphy.png") }],
  "johnny_juzang": [{ team: "min", image: require("../assets/images/nba-players/min/johnny_juzang.png") }, { team: "uta", image: require("../assets/images/nba-players/uta/johnny_juzang.png") }],
  "jonas_valanciunas": [{ team: "den", image: require("../assets/images/nba-players/den/jonas_valanciunas.png") }, { team: "was", image: require("../assets/images/nba-players/was/jonas_valanciunas.png") }],
  "jonathan_isaac": [{ team: "orl", image: require("../assets/images/nba-players/orl/jonathan_isaac.png") }],
  "jonathan_kuminga": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/jonathan_kuminga.png") }],
  "jonathan_mogbo": [{ team: "tor", image: require("../assets/images/nba-players/tor/jonathan_mogbo.png") }],
  "jordan_clarkson": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/jordan_clarkson.png") }, { team: "uta", image: require("../assets/images/nba-players/uta/jordan_clarkson.png") }],
  "jordan_goodwin": [{ team: "lal", image: require("../assets/images/nba-players/lal/jordan_goodwin.png") }, { team: "phx", image: require("../assets/images/nba-players/phx/jordan_goodwin.png") }],
  "jordan_hawkins": [{ team: "nop", image: require("../assets/images/nba-players/nop/jordan_hawkins.png") }],
  "jordan_mclaughlin": [{ team: "sac", image: require("../assets/images/nba-players/sac/jordan_mclaughlin.png") }, { team: "sas", image: require("../assets/images/nba-players/sas/jordan_mclaughlin.png") }],
  "jordan_miller": [{ team: "lac", image: require("../assets/images/nba-players/lac/jordan_miller.png") }],
  "jordan_poole": [{ team: "nop", image: require("../assets/images/nba-players/nop/jordan_poole.png") }, { team: "was", image: require("../assets/images/nba-players/was/jordan_poole.png") }],
  "jordan_tucker": [{ team: "phi", image: require("../assets/images/nba-players/phi/jordan_tucker.png") }],
  "jordan_walsh": [{ team: "bos", image: require("../assets/images/nba-players/bos/jordan_walsh.png") }],
  "jose_alvarado": [{ team: "nop", image: require("../assets/images/nba-players/nop/jose_alvarado.png") }],
  "josh_christopher": [{ team: "mia", image: require("../assets/images/nba-players/mia/josh_christopher.png") }],
  "josh_giddey": [{ team: "chi", image: require("../assets/images/nba-players/chi/josh_giddey.png") }],
  "josh_green": [{ team: "cha", image: require("../assets/images/nba-players/cha/josh_green.png") }],
  "josh_hart": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/josh_hart.png") }],
  "josh_minott": [{ team: "bos", image: require("../assets/images/nba-players/bos/josh_minott.png") }, { team: "min", image: require("../assets/images/nba-players/min/josh_minott.png") }],
  "josh_okogie": [{ team: "hou", image: require("../assets/images/nba-players/hou/josh_okogie.png") }, { team: "phx", image: require("../assets/images/nba-players/phx/josh_okogie.png") }],
  "jrue_holiday": [{ team: "bos", image: require("../assets/images/nba-players/bos/jrue_holiday.png") }, { team: "por", image: require("../assets/images/nba-players/por/jrue_holiday.png") }],
  "jt_thor": [{ team: "cle", image: require("../assets/images/nba-players/cle/jt_thor.png") }],
  "judah_mintz": [{ team: "phi", image: require("../assets/images/nba-players/phi/judah_mintz.png") }],
  "jules_bernard": [{ team: "cle", image: require("../assets/images/nba-players/cle/jules_bernard.png") }],
  "julian_champagnie": [{ team: "sas", image: require("../assets/images/nba-players/sas/julian_champagnie.png") }],
  "julian_phillips": [{ team: "chi", image: require("../assets/images/nba-players/chi/julian_phillips.png") }],
  "julian_strawther": [{ team: "den", image: require("../assets/images/nba-players/den/julian_strawther.png") }],
  "julius_randle": [{ team: "min", image: require("../assets/images/nba-players/min/julius_randle.png") }],
  "justin_champagnie": [{ team: "was", image: require("../assets/images/nba-players/was/justin_champagnie.png") }],
  "justin_edwards": [{ team: "phi", image: require("../assets/images/nba-players/phi/justin_edwards.png") }],
  "justin_minaya": [{ team: "por", image: require("../assets/images/nba-players/por/justin_minaya.png") }],
  "jusuf_nurki_": [{ team: "uta", image: require("../assets/images/nba-players/uta/jusuf_nurki_.png") }],
  "jusuf_nurkic": [{ team: "phx", image: require("../assets/images/nba-players/phx/jusuf_nurkic.png") }],
  "k_j__simpson": [{ team: "cha", image: require("../assets/images/nba-players/cha/k_j__simpson.png") }],
  "kai_jones": [{ team: "lac", image: require("../assets/images/nba-players/lac/kai_jones.png") }],
  "kam_jones": [{ team: "ind", image: require("../assets/images/nba-players/ind/kam_jones.png") }],
  "karl_anthony_towns": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/karl_anthony_towns.png") }],
  "karlo_matkovi_": [{ team: "nop", image: require("../assets/images/nba-players/nop/karlo_matkovi_.png") }],
  "karlo_matkovic": [{ team: "nop", image: require("../assets/images/nba-players/nop/karlo_matkovic.png") }],
  "kasparas_jaku_ionis": [{ team: "mia", image: require("../assets/images/nba-players/mia/kasparas_jaku_ionis.png") }],
  "kawhi_leonard": [{ team: "lac", image: require("../assets/images/nba-players/lac/kawhi_leonard.png") }],
  "keegan_murray": [{ team: "sac", image: require("../assets/images/nba-players/sac/keegan_murray.png") }],
  "keita_bates_diop": [{ team: "min", image: require("../assets/images/nba-players/min/keita_bates_diop.png") }],
  "kel_el_ware": [{ team: "mia", image: require("../assets/images/nba-players/mia/kel_el_ware.png") }],
  "keldon_johnson": [{ team: "sas", image: require("../assets/images/nba-players/sas/keldon_johnson.png") }],
  "kelel_ware": [{ team: "mia", image: require("../assets/images/nba-players/mia/kelel_ware.png") }],
  "kelly_olynyk": [{ team: "sas", image: require("../assets/images/nba-players/sas/kelly_olynyk.png") }, { team: "tor", image: require("../assets/images/nba-players/tor/kelly_olynyk.png") }],
  "kelly_oubre_jr": [{ team: "phi", image: require("../assets/images/nba-players/phi/kelly_oubre_jr.png") }],
  "kelly_oubre_jr_": [{ team: "phi", image: require("../assets/images/nba-players/phi/kelly_oubre_jr_.png") }],
  "kendall_brown": [{ team: "ind", image: require("../assets/images/nba-players/ind/kendall_brown.png") }],
  "kenneth_lofton_jr_": [{ team: "chi", image: require("../assets/images/nba-players/chi/kenneth_lofton_jr_.png") }],
  "kenrich_williams": [{ team: "okc", image: require("../assets/images/nba-players/okc/kenrich_williams.png") }],
  "kentavious_caldwell_pope": [{ team: "mem", image: require("../assets/images/nba-players/mem/kentavious_caldwell_pope.png") }, { team: "orl", image: require("../assets/images/nba-players/orl/kentavious_caldwell_pope.png") }],
  "kenyon_martin_jr_": [{ team: "phi", image: require("../assets/images/nba-players/phi/kenyon_martin_jr_.png") }],
  "keon_ellis": [{ team: "sac", image: require("../assets/images/nba-players/sac/keon_ellis.png") }],
  "keon_johnson": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/keon_johnson.png") }],
  "keshad_johnson": [{ team: "mia", image: require("../assets/images/nba-players/mia/keshad_johnson.png") }],
  "kessler_edwards": [{ team: "dal", image: require("../assets/images/nba-players/dal/kessler_edwards.png") }],
  "kevin_durant": [{ team: "hou", image: require("../assets/images/nba-players/hou/kevin_durant.png") }, { team: "phx", image: require("../assets/images/nba-players/phx/kevin_durant.png") }],
  "kevin_huerter": [{ team: "chi", image: require("../assets/images/nba-players/chi/kevin_huerter.png") }, { team: "sac", image: require("../assets/images/nba-players/sac/kevin_huerter.png") }],
  "kevin_knox_ii": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/kevin_knox_ii.png") }],
  "kevin_love": [{ team: "mia", image: require("../assets/images/nba-players/mia/kevin_love.png") }, { team: "uta", image: require("../assets/images/nba-players/uta/kevin_love.png") }],
  "kevin_mccullar_jr": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/kevin_mccullar_jr.png") }],
  "kevin_porter_jr": [{ team: "mil", image: require("../assets/images/nba-players/mil/kevin_porter_jr.png") }],
  "kevin_porter_jr_": [{ team: "lac", image: require("../assets/images/nba-players/lac/kevin_porter_jr_.png") }],
  "kevon_looney": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/kevon_looney.png") }, { team: "nop", image: require("../assets/images/nba-players/nop/kevon_looney.png") }],
  "keyontae_johnson": [{ team: "cha", image: require("../assets/images/nba-players/cha/keyontae_johnson.png") }],
  "keyonte_george": [{ team: "uta", image: require("../assets/images/nba-players/uta/keyonte_george.png") }],
  "khaman_maluach": [{ team: "phx", image: require("../assets/images/nba-players/phx/khaman_maluach.png") }],
  "khris_middleton": [{ team: "was", image: require("../assets/images/nba-players/was/khris_middleton.png") }],
  "kira_lewis_jr_": [{ team: "was", image: require("../assets/images/nba-players/was/kira_lewis_jr_.png") }],
  "kj_simpson": [{ team: "cha", image: require("../assets/images/nba-players/cha/kj_simpson.png") }],
  "klay_thompson": [{ team: "dal", image: require("../assets/images/nba-players/dal/klay_thompson.png") }],
  "kobe_brown": [{ team: "lac", image: require("../assets/images/nba-players/lac/kobe_brown.png") }],
  "kobe_bufkin": [{ team: "lal", image: require("../assets/images/nba-players/lal/kobe_bufkin.png") }],
  "kobe_sanders": [{ team: "lac", image: require("../assets/images/nba-players/lac/kobe_sanders.png") }],
  "koby_brea": [{ team: "phx", image: require("../assets/images/nba-players/phx/koby_brea.png") }],
  "kon_knueppel": [{ team: "cha", image: require("../assets/images/nba-players/cha/kon_knueppel.png") }],
  "kris_dunn": [{ team: "lac", image: require("../assets/images/nba-players/lac/kris_dunn.png") }],
  "kris_murray": [{ team: "por", image: require("../assets/images/nba-players/por/kris_murray.png") }],
  "kristaps_porzingis": [{ team: "bos", image: require("../assets/images/nba-players/bos/kristaps_porzingis.png") }],
  "kyle_anderson": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/kyle_anderson.png") }, { team: "uta", image: require("../assets/images/nba-players/uta/kyle_anderson.png") }],
  "kyle_filipowski": [{ team: "uta", image: require("../assets/images/nba-players/uta/kyle_filipowski.png") }],
  "kyle_kuzma": [{ team: "mil", image: require("../assets/images/nba-players/mil/kyle_kuzma.png") }, { team: "was", image: require("../assets/images/nba-players/was/kyle_kuzma.png") }],
  "kyle_lowry": [{ team: "phi", image: require("../assets/images/nba-players/phi/kyle_lowry.png") }],
  "kylor_kelley": [{ team: "lal", image: require("../assets/images/nba-players/lal/kylor_kelley.png") }],
  "kyrie_irving": [{ team: "dal", image: require("../assets/images/nba-players/dal/kyrie_irving.png") }],
  "kyshawn_george": [{ team: "was", image: require("../assets/images/nba-players/was/kyshawn_george.png") }],
  "lachlan_olbrich": [{ team: "chi", image: require("../assets/images/nba-players/chi/lachlan_olbrich.png") }],
  "lamar_stevens": [{ team: "det", image: require("../assets/images/nba-players/det/lamar_stevens.png") }],
  "lamelo_ball": [{ team: "cha", image: require("../assets/images/nba-players/cha/lamelo_ball.png") }],
  "landry_shamet": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/landry_shamet.png") }],
  "larry_nance_jr": [{ team: "cle", image: require("../assets/images/nba-players/cle/larry_nance_jr.png") }],
  "lauri_markkanen": [{ team: "uta", image: require("../assets/images/nba-players/uta/lauri_markkanen.png") }],
  "lebron_james": [{ team: "lal", image: require("../assets/images/nba-players/lal/lebron_james.png") }],
  "leonard_miller": [{ team: "min", image: require("../assets/images/nba-players/min/leonard_miller.png") }],
  "lester_quinones": [{ team: "phi", image: require("../assets/images/nba-players/phi/lester_quinones.png") }],
  "liam_mcneeley": [{ team: "cha", image: require("../assets/images/nba-players/cha/liam_mcneeley.png") }],
  "liam_robbins": [{ team: "mil", image: require("../assets/images/nba-players/mil/liam_robbins.png") }],
  "lindy_waters_iii": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/lindy_waters_iii.png") }, { team: "sas", image: require("../assets/images/nba-players/sas/lindy_waters_iii.png") }],
  "lj_cryer": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/lj_cryer.png") }],
  "lonnie_walker_iv": [{ team: "bos", image: require("../assets/images/nba-players/bos/lonnie_walker_iv.png") }],
  "lonzo_ball": [{ team: "chi", image: require("../assets/images/nba-players/chi/lonzo_ball.png") }, { team: "cle", image: require("../assets/images/nba-players/cle/lonzo_ball.png") }],
  "luguentz_dort": [{ team: "okc", image: require("../assets/images/nba-players/okc/luguentz_dort.png") }],
  "luka_doncic": [{ team: "dal", image: require("../assets/images/nba-players/dal/luka_doncic.png") }, { team: "lal", image: require("../assets/images/nba-players/lal/luka_doncic.png") }],
  "luka_garza": [{ team: "bos", image: require("../assets/images/nba-players/bos/luka_garza.png") }, { team: "min", image: require("../assets/images/nba-players/min/luka_garza.png") }],
  "luke_kennard": [{ team: "mem", image: require("../assets/images/nba-players/mem/luke_kennard.png") }],
  "luke_kornet": [{ team: "bos", image: require("../assets/images/nba-players/bos/luke_kornet.png") }, { team: "sas", image: require("../assets/images/nba-players/sas/luke_kornet.png") }],
  "luke_travers": [{ team: "cle", image: require("../assets/images/nba-players/cle/luke_travers.png") }],
  "m__pereira": [{ team: "mem", image: require("../assets/images/nba-players/mem/m__pereira.png") }],
  "m__wood": [{ team: "phx", image: require("../assets/images/nba-players/phx/m__wood.png") }],
  "malachi_flynn": [{ team: "sas", image: require("../assets/images/nba-players/sas/malachi_flynn.png") }],
  "malaki_branham": [{ team: "sas", image: require("../assets/images/nba-players/sas/malaki_branham.png") }, { team: "was", image: require("../assets/images/nba-players/was/malaki_branham.png") }],
  "malcolm_brogdon": [{ team: "was", image: require("../assets/images/nba-players/was/malcolm_brogdon.png") }],
  "malcolm_hill": [{ team: "nop", image: require("../assets/images/nba-players/nop/malcolm_hill.png") }],
  "malevy_leons": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/malevy_leons.png") }, { team: "okc", image: require("../assets/images/nba-players/okc/malevy_leons.png") }],
  "malik_beasley": [{ team: "det", image: require("../assets/images/nba-players/det/malik_beasley.png") }],
  "malik_monk": [{ team: "sac", image: require("../assets/images/nba-players/sac/malik_monk.png") }],
  "mamadi_diakite": [{ team: "phx", image: require("../assets/images/nba-players/phx/mamadi_diakite.png") }],
  "marcus_sasser": [{ team: "det", image: require("../assets/images/nba-players/det/marcus_sasser.png") }],
  "marcus_smart": [{ team: "lal", image: require("../assets/images/nba-players/lal/marcus_smart.png") }, { team: "mem", image: require("../assets/images/nba-players/mem/marcus_smart.png") }],
  "marjon_beauchamp": [{ team: "mil", image: require("../assets/images/nba-players/mil/marjon_beauchamp.png") }, { team: "phi", image: require("../assets/images/nba-players/phi/marjon_beauchamp.png") }],
  "mark_williams": [{ team: "phx", image: require("../assets/images/nba-players/phx/mark_williams.png") }],
  "markieff_morris": [{ team: "dal", image: require("../assets/images/nba-players/dal/markieff_morris.png") }],
  "markquis_nowell": [{ team: "hou", image: require("../assets/images/nba-players/hou/markquis_nowell.png") }],
  "marvin_bagley_iii": [{ team: "was", image: require("../assets/images/nba-players/was/marvin_bagley_iii.png") }],
  "mason_jones": [{ team: "sac", image: require("../assets/images/nba-players/sac/mason_jones.png") }],
  "mason_plumlee": [{ team: "cha", image: require("../assets/images/nba-players/cha/mason_plumlee.png") }, { team: "phx", image: require("../assets/images/nba-players/phx/mason_plumlee.png") }],
  "matas_buzelis": [{ team: "chi", image: require("../assets/images/nba-players/chi/matas_buzelis.png") }],
  "matisse_thybulle": [{ team: "por", image: require("../assets/images/nba-players/por/matisse_thybulle.png") }],
  "matt_ryan": [{ team: "nop", image: require("../assets/images/nba-players/nop/matt_ryan.png") }, { team: "nyk", image: require("../assets/images/nba-players/nyk/matt_ryan.png") }],
  "max_christie": [{ team: "dal", image: require("../assets/images/nba-players/dal/max_christie.png") }, { team: "lal", image: require("../assets/images/nba-players/lal/max_christie.png") }],
  "max_fiedler": [{ team: "phi", image: require("../assets/images/nba-players/phi/max_fiedler.png") }],
  "max_shulga": [{ team: "bos", image: require("../assets/images/nba-players/bos/max_shulga.png") }],
  "max_strus": [{ team: "cle", image: require("../assets/images/nba-players/cle/max_strus.png") }],
  "maxi_kleber": [{ team: "dal", image: require("../assets/images/nba-players/dal/maxi_kleber.png") }, { team: "lal", image: require("../assets/images/nba-players/lal/maxi_kleber.png") }],
  "maxime_raynaud": [{ team: "sac", image: require("../assets/images/nba-players/sac/maxime_raynaud.png") }],
  "maxwell_lewis": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/maxwell_lewis.png") }, { team: "lal", image: require("../assets/images/nba-players/lal/maxwell_lewis.png") }],
  "micah_peavy": [{ team: "nop", image: require("../assets/images/nba-players/nop/micah_peavy.png") }],
  "micah_potter": [{ team: "ind", image: require("../assets/images/nba-players/ind/micah_potter.png") }, { team: "uta", image: require("../assets/images/nba-players/uta/micah_potter.png") }],
  "michael_porter_jr": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/michael_porter_jr.png") }],
  "michael_porter_jr_": [{ team: "den", image: require("../assets/images/nba-players/den/michael_porter_jr_.png") }],
  "mikal_bridges": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/mikal_bridges.png") }],
  "mike_conley": [{ team: "min", image: require("../assets/images/nba-players/min/mike_conley.png") }],
  "miles_bridges": [{ team: "cha", image: require("../assets/images/nba-players/cha/miles_bridges.png") }],
  "miles_kelly": [{ team: "dal", image: require("../assets/images/nba-players/dal/miles_kelly.png") }],
  "miles_mcbride": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/miles_mcbride.png") }],
  "miles_norris": [{ team: "mem", image: require("../assets/images/nba-players/mem/miles_norris.png") }],
  "miller_kopp": [{ team: "okc", image: require("../assets/images/nba-players/okc/miller_kopp.png") }],
  "mitchell_robinson": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/mitchell_robinson.png") }],
  "miye_oni": [{ team: "mem", image: require("../assets/images/nba-players/mem/miye_oni.png") }],
  "mohamed_diawara": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/mohamed_diawara.png") }],
  "monte_morris": [{ team: "phx", image: require("../assets/images/nba-players/phx/monte_morris.png") }],
  "moritz_wagner": [{ team: "orl", image: require("../assets/images/nba-players/orl/moritz_wagner.png") }],
  "moses_brown": [{ team: "ind", image: require("../assets/images/nba-players/ind/moses_brown.png") }, { team: "nyk", image: require("../assets/images/nba-players/nyk/moses_brown.png") }],
  "moses_moody": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/moses_moody.png") }],
  "moussa_cisse": [{ team: "dal", image: require("../assets/images/nba-players/dal/moussa_cisse.png") }],
  "moussa_diabat_": [{ team: "cha", image: require("../assets/images/nba-players/cha/moussa_diabat_.png") }],
  "moussa_diabate": [{ team: "cha", image: require("../assets/images/nba-players/cha/moussa_diabate.png") }],
  "myles_turner": [{ team: "ind", image: require("../assets/images/nba-players/ind/myles_turner.png") }, { team: "mil", image: require("../assets/images/nba-players/mil/myles_turner.png") }],
  "myron_gardner": [{ team: "mia", image: require("../assets/images/nba-players/mia/myron_gardner.png") }],
  "n_faly_dante": [{ team: "hou", image: require("../assets/images/nba-players/hou/n_faly_dante.png") }],
  "naeqwan_tomlin": [{ team: "cle", image: require("../assets/images/nba-players/cle/naeqwan_tomlin.png") }],
  "naji_marshall": [{ team: "dal", image: require("../assets/images/nba-players/dal/naji_marshall.png") }],
  "nassir_little": [{ team: "mia", image: require("../assets/images/nba-players/mia/nassir_little.png") }],
  "nate_darling": [{ team: "lac", image: require("../assets/images/nba-players/lac/nate_darling.png") }],
  "nate_hinton": [{ team: "hou", image: require("../assets/images/nba-players/hou/nate_hinton.png") }],
  "nathan_mensah": [{ team: "sas", image: require("../assets/images/nba-players/sas/nathan_mensah.png") }],
  "naz_reid": [{ team: "min", image: require("../assets/images/nba-players/min/naz_reid.png") }],
  "neemias_queta": [{ team: "bos", image: require("../assets/images/nba-players/bos/neemias_queta.png") }],
  "nic_claxton": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/nic_claxton.png") }],
  "nick_jr__smith": [{ team: "cha", image: require("../assets/images/nba-players/cha/nick_jr__smith.png") }],
  "nick_richards": [{ team: "cha", image: require("../assets/images/nba-players/cha/nick_richards.png") }, { team: "phx", image: require("../assets/images/nba-players/phx/nick_richards.png") }],
  "nick_smith_jr": [{ team: "lal", image: require("../assets/images/nba-players/lal/nick_smith_jr.png") }],
  "nickeil_alexander_walker": [{ team: "min", image: require("../assets/images/nba-players/min/nickeil_alexander_walker.png") }],
  "nicolas_batum": [{ team: "lac", image: require("../assets/images/nba-players/lac/nicolas_batum.png") }],
  "nigel_hayes_davis": [{ team: "phx", image: require("../assets/images/nba-players/phx/nigel_hayes_davis.png") }],
  "nikola_joki_": [{ team: "den", image: require("../assets/images/nba-players/den/nikola_joki_.png") }],
  "nikola_jokic": [{ team: "den", image: require("../assets/images/nba-players/den/nikola_jokic.png") }],
  "nikola_jovi_": [{ team: "mia", image: require("../assets/images/nba-players/mia/nikola_jovi_.png") }],
  "nikola_jovic": [{ team: "mia", image: require("../assets/images/nba-players/mia/nikola_jovic.png") }],
  "nikola_topi_": [{ team: "okc", image: require("../assets/images/nba-players/okc/nikola_topi_.png") }],
  "nikola_vu_evi_": [{ team: "chi", image: require("../assets/images/nba-players/chi/nikola_vu_evi_.png") }],
  "nikola_vucevic": [{ team: "chi", image: require("../assets/images/nba-players/chi/nikola_vucevic.png") }],
  "nique_clifford": [{ team: "sac", image: require("../assets/images/nba-players/sac/nique_clifford.png") }],
  "noa_essengue": [{ team: "chi", image: require("../assets/images/nba-players/chi/noa_essengue.png") }],
  "noah_clowney": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/noah_clowney.png") }],
  "noah_penda": [{ team: "orl", image: require("../assets/images/nba-players/orl/noah_penda.png") }],
  "nolan_traore": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/nolan_traore.png") }],
  "norman_powell": [{ team: "lac", image: require("../assets/images/nba-players/lac/norman_powell.png") }, { team: "mia", image: require("../assets/images/nba-players/mia/norman_powell.png") }],
  "o_g__anunoby": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/o_g__anunoby.png") }],
  "obi_toppin": [{ team: "ind", image: require("../assets/images/nba-players/ind/obi_toppin.png") }],
  "ochai_agbaji": [{ team: "tor", image: require("../assets/images/nba-players/tor/ochai_agbaji.png") }],
  "og_anunoby": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/og_anunoby.png") }],
  "olivier_maxence_prosper": [{ team: "mem", image: require("../assets/images/nba-players/mem/olivier_maxence_prosper.png") }],
  "oliviermaxence_prosper": [{ team: "dal", image: require("../assets/images/nba-players/dal/oliviermaxence_prosper.png") }],
  "onuralp_bitim": [{ team: "chi", image: require("../assets/images/nba-players/chi/onuralp_bitim.png") }],
  "orlando_robinson": [{ team: "orl", image: require("../assets/images/nba-players/orl/orlando_robinson.png") }],
  "oscar_tshiebwe": [{ team: "uta", image: require("../assets/images/nba-players/uta/oscar_tshiebwe.png") }],
  "oso_ighodaro": [{ team: "phx", image: require("../assets/images/nba-players/phx/oso_ighodaro.png") }],
  "ousmane_dieng": [{ team: "okc", image: require("../assets/images/nba-players/okc/ousmane_dieng.png") }],
  "p_j__dozier": [{ team: "min", image: require("../assets/images/nba-players/min/p_j__dozier.png") }],
  "p_j__washington": [{ team: "dal", image: require("../assets/images/nba-players/dal/p_j__washington.png") }],
  "pac_me_dadiet": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/pac_me_dadiet.png") }],
  "pacome_dadiet": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/pacome_dadiet.png") }],
  "paolo_banchero": [{ team: "orl", image: require("../assets/images/nba-players/orl/paolo_banchero.png") }],
  "pascal_siakam": [{ team: "ind", image: require("../assets/images/nba-players/ind/pascal_siakam.png") }],
  "pat_connaughton": [{ team: "cha", image: require("../assets/images/nba-players/cha/pat_connaughton.png") }, { team: "mil", image: require("../assets/images/nba-players/mil/pat_connaughton.png") }],
  "pat_spencer": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/pat_spencer.png") }],
  "patrick_baldwin_jr_": [{ team: "was", image: require("../assets/images/nba-players/was/patrick_baldwin_jr_.png") }],
  "patrick_williams": [{ team: "chi", image: require("../assets/images/nba-players/chi/patrick_williams.png") }],
  "patty_mills": [{ team: "uta", image: require("../assets/images/nba-players/uta/patty_mills.png") }],
  "paul_george": [{ team: "phi", image: require("../assets/images/nba-players/phi/paul_george.png") }],
  "paul_reed": [{ team: "det", image: require("../assets/images/nba-players/det/paul_reed.png") }],
  "payton_pritchard": [{ team: "bos", image: require("../assets/images/nba-players/bos/payton_pritchard.png") }],
  "pelle_larsson": [{ team: "mia", image: require("../assets/images/nba-players/mia/pelle_larsson.png") }],
  "pete_nance": [{ team: "cle", image: require("../assets/images/nba-players/cle/pete_nance.png") }, { team: "mil", image: require("../assets/images/nba-players/mil/pete_nance.png") }],
  "peyton_watson": [{ team: "den", image: require("../assets/images/nba-players/den/peyton_watson.png") }],
  "pj_hall": [{ team: "cha", image: require("../assets/images/nba-players/cha/pj_hall.png") }, { team: "den", image: require("../assets/images/nba-players/den/pj_hall.png") }],
  "pj_washington": [{ team: "dal", image: require("../assets/images/nba-players/dal/pj_washington.png") }],
  "precious_achiuwa": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/precious_achiuwa.png") }, { team: "sac", image: require("../assets/images/nba-players/sac/precious_achiuwa.png") }],
  "q__post": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/q__post.png") }],
  "quentin_grimes": [{ team: "dal", image: require("../assets/images/nba-players/dal/quentin_grimes.png") }, { team: "phi", image: require("../assets/images/nba-players/phi/quentin_grimes.png") }],
  "quenton_jackson": [{ team: "ind", image: require("../assets/images/nba-players/ind/quenton_jackson.png") }],
  "quincy_olivari": [{ team: "lal", image: require("../assets/images/nba-players/lal/quincy_olivari.png") }],
  "quinten_post": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/quinten_post.png") }],
  "r__rupert": [{ team: "por", image: require("../assets/images/nba-players/por/r__rupert.png") }],
  "rasheer_fleming": [{ team: "phx", image: require("../assets/images/nba-players/phx/rasheer_fleming.png") }],
  "rayan_rupert": [{ team: "por", image: require("../assets/images/nba-players/por/rayan_rupert.png") }],
  "rayj_dennis": [{ team: "lac", image: require("../assets/images/nba-players/lac/rayj_dennis.png") }],
  "reece_beekman": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/reece_beekman.png") }, { team: "gsw", image: require("../assets/images/nba-players/gsw/reece_beekman.png") }],
  "reed_sheppard": [{ team: "hou", image: require("../assets/images/nba-players/hou/reed_sheppard.png") }],
  "reggie_jackson": [{ team: "phi", image: require("../assets/images/nba-players/phi/reggie_jackson.png") }],
  "richaun_holmes": [{ team: "was", image: require("../assets/images/nba-players/was/richaun_holmes.png") }],
  "ricky_iv_council": [{ team: "phi", image: require("../assets/images/nba-players/phi/ricky_iv_council.png") }],
  "riley_minix": [{ team: "sas", image: require("../assets/images/nba-players/sas/riley_minix.png") }],
  "rj_barrett": [{ team: "tor", image: require("../assets/images/nba-players/tor/rj_barrett.png") }],
  "rob_dillingham": [{ team: "min", image: require("../assets/images/nba-players/min/rob_dillingham.png") }],
  "robert_williams_iii": [{ team: "por", image: require("../assets/images/nba-players/por/robert_williams_iii.png") }],
  "rocco_zikarsky": [{ team: "min", image: require("../assets/images/nba-players/min/rocco_zikarsky.png") }],
  "ron_harper_jr": [{ team: "bos", image: require("../assets/images/nba-players/bos/ron_harper_jr.png") }],
  "ron_harper_jr_": [{ team: "bos", image: require("../assets/images/nba-players/bos/ron_harper_jr_.png") }],
  "ron_ii_holland": [{ team: "det", image: require("../assets/images/nba-players/det/ron_ii_holland.png") }],
  "ronald_holland_ii": [{ team: "det", image: require("../assets/images/nba-players/det/ronald_holland_ii.png") }],
  "royce_o_neale": [{ team: "phx", image: require("../assets/images/nba-players/phx/royce_o_neale.png") }],
  "royce_oneale": [{ team: "phx", image: require("../assets/images/nba-players/phx/royce_oneale.png") }],
  "rudy_gobert": [{ team: "min", image: require("../assets/images/nba-players/min/rudy_gobert.png") }],
  "rui_hachimura": [{ team: "lal", image: require("../assets/images/nba-players/lal/rui_hachimura.png") }],
  "russell_westbrook": [{ team: "den", image: require("../assets/images/nba-players/den/russell_westbrook.png") }, { team: "sac", image: require("../assets/images/nba-players/sac/russell_westbrook.png") }],
  "ryan_dunn": [{ team: "phx", image: require("../assets/images/nba-players/phx/ryan_dunn.png") }],
  "ryan_kalkbrenner": [{ team: "cha", image: require("../assets/images/nba-players/cha/ryan_kalkbrenner.png") }],
  "ryan_nembhard": [{ team: "dal", image: require("../assets/images/nba-players/dal/ryan_nembhard.png") }],
  "ryan_rollins": [{ team: "mil", image: require("../assets/images/nba-players/mil/ryan_rollins.png") }],
  "saddiq_bey": [{ team: "nop", image: require("../assets/images/nba-players/nop/saddiq_bey.png") }],
  "sam_hauser": [{ team: "bos", image: require("../assets/images/nba-players/bos/sam_hauser.png") }],
  "sam_merrill": [{ team: "cle", image: require("../assets/images/nba-players/cle/sam_merrill.png") }],
  "samardo_samuels": [{ team: "hou", image: require("../assets/images/nba-players/hou/samardo_samuels.png") }],
  "sandro_mamukelashvili": [{ team: "sas", image: require("../assets/images/nba-players/sas/sandro_mamukelashvili.png") }, { team: "tor", image: require("../assets/images/nba-players/tor/sandro_mamukelashvili.png") }],
  "santi_aldama": [{ team: "mem", image: require("../assets/images/nba-players/mem/santi_aldama.png") }],
  "scoot_henderson": [{ team: "por", image: require("../assets/images/nba-players/por/scoot_henderson.png") }],
  "scottie_barnes": [{ team: "tor", image: require("../assets/images/nba-players/tor/scottie_barnes.png") }],
  "scotty_pippen_jr": [{ team: "mem", image: require("../assets/images/nba-players/mem/scotty_pippen_jr.png") }],
  "scotty_pippen_jr_": [{ team: "mem", image: require("../assets/images/nba-players/mem/scotty_pippen_jr_.png") }],
  "seth_curry": [{ team: "cha", image: require("../assets/images/nba-players/cha/seth_curry.png") }, { team: "gsw", image: require("../assets/images/nba-players/gsw/seth_curry.png") }],
  "shaedon_sharpe": [{ team: "por", image: require("../assets/images/nba-players/por/shaedon_sharpe.png") }],
  "shai_gilgeous_alexander": [{ team: "okc", image: require("../assets/images/nba-players/okc/shai_gilgeous_alexander.png") }],
  "shake_milton": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/shake_milton.png") }],
  "sharife_cooper": [{ team: "was", image: require("../assets/images/nba-players/was/sharife_cooper.png") }],
  "sidy_cissoko": [{ team: "por", image: require("../assets/images/nba-players/por/sidy_cissoko.png") }, { team: "sas", image: require("../assets/images/nba-players/sas/sidy_cissoko.png") }],
  "simone_fontecchio": [{ team: "det", image: require("../assets/images/nba-players/det/simone_fontecchio.png") }, { team: "mia", image: require("../assets/images/nba-players/mia/simone_fontecchio.png") }],
  "sion_james": [{ team: "cha", image: require("../assets/images/nba-players/cha/sion_james.png") }],
  "skal_labissiere": [{ team: "sac", image: require("../assets/images/nba-players/sac/skal_labissiere.png") }],
  "spencer_dinwiddie": [{ team: "dal", image: require("../assets/images/nba-players/dal/spencer_dinwiddie.png") }],
  "spencer_jones": [{ team: "den", image: require("../assets/images/nba-players/den/spencer_jones.png") }],
  "stanley_umude": [{ team: "mil", image: require("../assets/images/nba-players/mil/stanley_umude.png") }, { team: "sas", image: require("../assets/images/nba-players/sas/stanley_umude.png") }],
  "stephen_curry": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/stephen_curry.png") }],
  "stephon_castle": [{ team: "sas", image: require("../assets/images/nba-players/sas/stephon_castle.png") }],
  "steven_adams": [{ team: "hou", image: require("../assets/images/nba-players/hou/steven_adams.png") }],
  "svi_mykhailiuk": [{ team: "uta", image: require("../assets/images/nba-players/uta/svi_mykhailiuk.png") }],
  "t__funk": [{ team: "was", image: require("../assets/images/nba-players/was/t__funk.png") }],
  "t__vukcevic": [{ team: "was", image: require("../assets/images/nba-players/was/t__vukcevic.png") }],
  "t_j__mcconnell": [{ team: "ind", image: require("../assets/images/nba-players/ind/t_j__mcconnell.png") }],
  "t_j__warren": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/t_j__warren.png") }],
  "taelon_peter": [{ team: "ind", image: require("../assets/images/nba-players/ind/taelon_peter.png") }],
  "taj_gibson": [{ team: "cha", image: require("../assets/images/nba-players/cha/taj_gibson.png") }],
  "talen_horton_tucker": [{ team: "chi", image: require("../assets/images/nba-players/chi/talen_horton_tucker.png") }],
  "tamar_bates": [{ team: "den", image: require("../assets/images/nba-players/den/tamar_bates.png") }],
  "tari_eason": [{ team: "hou", image: require("../assets/images/nba-players/hou/tari_eason.png") }],
  "taurean_prince": [{ team: "mil", image: require("../assets/images/nba-players/mil/taurean_prince.png") }],
  "taylor_hendricks": [{ team: "uta", image: require("../assets/images/nba-players/uta/taylor_hendricks.png") }],
  "taze_moore": [{ team: "por", image: require("../assets/images/nba-players/por/taze_moore.png") }],
  "terance_mann": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/terance_mann.png") }, { team: "lac", image: require("../assets/images/nba-players/lac/terance_mann.png") }],
  "terence_davis": [{ team: "mil", image: require("../assets/images/nba-players/mil/terence_davis.png") }],
  "terrence_jr__shannon": [{ team: "min", image: require("../assets/images/nba-players/min/terrence_jr__shannon.png") }],
  "terrence_shannon_jr": [{ team: "min", image: require("../assets/images/nba-players/min/terrence_shannon_jr.png") }],
  "terry_rozier": [{ team: "mia", image: require("../assets/images/nba-players/mia/terry_rozier.png") }],
  "terry_taylor": [{ team: "sac", image: require("../assets/images/nba-players/sac/terry_taylor.png") }],
  "thanasis_antetokounmpo": [{ team: "mil", image: require("../assets/images/nba-players/mil/thanasis_antetokounmpo.png") }],
  "thomas_bryant": [{ team: "cle", image: require("../assets/images/nba-players/cle/thomas_bryant.png") }, { team: "mia", image: require("../assets/images/nba-players/mia/thomas_bryant.png") }],
  "thomas_sorber": [{ team: "okc", image: require("../assets/images/nba-players/okc/thomas_sorber.png") }],
  "tidjane_sala_n": [{ team: "cha", image: require("../assets/images/nba-players/cha/tidjane_sala_n.png") }],
  "tidjane_salaun": [{ team: "cha", image: require("../assets/images/nba-players/cha/tidjane_salaun.png") }],
  "tim_hardaway_jr": [{ team: "den", image: require("../assets/images/nba-players/den/tim_hardaway_jr.png") }],
  "tim_hardaway_jr_": [{ team: "det", image: require("../assets/images/nba-players/det/tim_hardaway_jr_.png") }],
  "tj_mcconnell": [{ team: "ind", image: require("../assets/images/nba-players/ind/tj_mcconnell.png") }],
  "tobias_harris": [{ team: "det", image: require("../assets/images/nba-players/det/tobias_harris.png") }],
  "tolu_smith": [{ team: "det", image: require("../assets/images/nba-players/det/tolu_smith.png") }],
  "tony_bradley": [{ team: "ind", image: require("../assets/images/nba-players/ind/tony_bradley.png") }],
  "torrey_craig": [{ team: "chi", image: require("../assets/images/nba-players/chi/torrey_craig.png") }],
  "tosan_evbuomwan": [{ team: "det", image: require("../assets/images/nba-players/det/tosan_evbuomwan.png") }],
  "toumani_camara": [{ team: "por", image: require("../assets/images/nba-players/por/toumani_camara.png") }],
  "trae_young": [{ team: "was", image: require("../assets/images/nba-players/was/trae_young.png") }],
  "trayce_jackson_davis": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/trayce_jackson_davis.png") }],
  "trayce_jacksondavis": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/trayce_jacksondavis.png") }],
  "tre_johnson": [{ team: "was", image: require("../assets/images/nba-players/was/tre_johnson.png") }],
  "tre_jones": [{ team: "chi", image: require("../assets/images/nba-players/chi/tre_jones.png") }, { team: "sas", image: require("../assets/images/nba-players/sas/tre_jones.png") }],
  "tre_mann": [{ team: "cha", image: require("../assets/images/nba-players/cha/tre_mann.png") }],
  "trendon_watford": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/trendon_watford.png") }, { team: "phi", image: require("../assets/images/nba-players/phi/trendon_watford.png") }],
  "trevelin_queen": [{ team: "orl", image: require("../assets/images/nba-players/orl/trevelin_queen.png") }],
  "trey_alexander": [{ team: "den", image: require("../assets/images/nba-players/den/trey_alexander.png") }, { team: "nop", image: require("../assets/images/nba-players/nop/trey_alexander.png") }],
  "trey_jemison": [{ team: "nop", image: require("../assets/images/nba-players/nop/trey_jemison.png") }],
  "trey_jemison_iii": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/trey_jemison_iii.png") }],
  "trey_lyles": [{ team: "sac", image: require("../assets/images/nba-players/sac/trey_lyles.png") }],
  "trey_murphy_iii": [{ team: "nop", image: require("../assets/images/nba-players/nop/trey_murphy_iii.png") }],
  "tristan_da_silva": [{ team: "orl", image: require("../assets/images/nba-players/orl/tristan_da_silva.png") }],
  "tristan_silva_da": [{ team: "orl", image: require("../assets/images/nba-players/orl/tristan_silva_da.png") }],
  "tristan_thompson": [{ team: "cle", image: require("../assets/images/nba-players/cle/tristan_thompson.png") }],
  "tristan_vukcevic": [{ team: "was", image: require("../assets/images/nba-players/was/tristan_vukcevic.png") }],
  "tristen_newton": [{ team: "hou", image: require("../assets/images/nba-players/hou/tristen_newton.png") }, { team: "ind", image: require("../assets/images/nba-players/ind/tristen_newton.png") }],
  "ty_jerome": [{ team: "cle", image: require("../assets/images/nba-players/cle/ty_jerome.png") }, { team: "mem", image: require("../assets/images/nba-players/mem/ty_jerome.png") }],
  "tyler_herro": [{ team: "mia", image: require("../assets/images/nba-players/mia/tyler_herro.png") }],
  "tyler_kolek": [{ team: "nyk", image: require("../assets/images/nba-players/nyk/tyler_kolek.png") }],
  "tyler_smith": [{ team: "mil", image: require("../assets/images/nba-players/mil/tyler_smith.png") }],
  "tyrese_haliburton": [{ team: "ind", image: require("../assets/images/nba-players/ind/tyrese_haliburton.png") }],
  "tyrese_martin": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/tyrese_martin.png") }],
  "tyrese_maxey": [{ team: "phi", image: require("../assets/images/nba-players/phi/tyrese_maxey.png") }],
  "tyrese_proctor": [{ team: "cle", image: require("../assets/images/nba-players/cle/tyrese_proctor.png") }],
  "tyson_etienne": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/tyson_etienne.png") }],
  "tyty_washington_jr": [{ team: "lac", image: require("../assets/images/nba-players/lac/tyty_washington_jr.png") }],
  "tyty_washington_jr_": [{ team: "phx", image: require("../assets/images/nba-players/phx/tyty_washington_jr_.png") }],
  "tyus_jones": [{ team: "orl", image: require("../assets/images/nba-players/orl/tyus_jones.png") }, { team: "phx", image: require("../assets/images/nba-players/phx/tyus_jones.png") }],
  "ulrich_chomche": [{ team: "tor", image: require("../assets/images/nba-players/tor/ulrich_chomche.png") }],
  "vasilije_micic": [{ team: "cha", image: require("../assets/images/nba-players/cha/vasilije_micic.png") }],
  "victor_wembanyama": [{ team: "sas", image: require("../assets/images/nba-players/sas/victor_wembanyama.png") }],
  "vince_williams_jr": [{ team: "mem", image: require("../assets/images/nba-players/mem/vince_williams_jr.png") }],
  "vince_williams_jr_": [{ team: "mem", image: require("../assets/images/nba-players/mem/vince_williams_jr_.png") }],
  "vj_edgecombe": [{ team: "phi", image: require("../assets/images/nba-players/phi/vj_edgecombe.png") }],
  "vladislav_goldin": [{ team: "mia", image: require("../assets/images/nba-players/mia/vladislav_goldin.png") }],
  "vlatko_cancar": [{ team: "den", image: require("../assets/images/nba-players/den/vlatko_cancar.png") }],
  "w__richardson": [{ team: "den", image: require("../assets/images/nba-players/den/w__richardson.png") }],
  "walker_kessler": [{ team: "uta", image: require("../assets/images/nba-players/uta/walker_kessler.png") }],
  "walter_clayton_jr": [{ team: "uta", image: require("../assets/images/nba-players/uta/walter_clayton_jr.png") }],
  "wendell_carter_jr": [{ team: "orl", image: require("../assets/images/nba-players/orl/wendell_carter_jr.png") }],
  "wendell_carter_jr_": [{ team: "orl", image: require("../assets/images/nba-players/orl/wendell_carter_jr_.png") }],
  "wendell_moore_jr": [{ team: "det", image: require("../assets/images/nba-players/det/wendell_moore_jr.png") }],
  "wendell_moore_jr_": [{ team: "det", image: require("../assets/images/nba-players/det/wendell_moore_jr_.png") }],
  "will_richard": [{ team: "gsw", image: require("../assets/images/nba-players/gsw/will_richard.png") }],
  "will_riley": [{ team: "was", image: require("../assets/images/nba-players/was/will_riley.png") }],
  "xavier_tillman": [{ team: "bos", image: require("../assets/images/nba-players/bos/xavier_tillman.png") }],
  "yang_hansen": [{ team: "por", image: require("../assets/images/nba-players/por/yang_hansen.png") }],
  "yanic_konan_niederh_user": [{ team: "lac", image: require("../assets/images/nba-players/lac/yanic_konan_niederh_user.png") }],
  "yongxi_cui": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/yongxi_cui.png") }],
  "yuki_kawamura": [{ team: "chi", image: require("../assets/images/nba-players/chi/yuki_kawamura.png") }, { team: "mem", image: require("../assets/images/nba-players/mem/yuki_kawamura.png") }],
  "yves_missi": [{ team: "nop", image: require("../assets/images/nba-players/nop/yves_missi.png") }],
  "zach_collins": [{ team: "chi", image: require("../assets/images/nba-players/chi/zach_collins.png") }, { team: "sas", image: require("../assets/images/nba-players/sas/zach_collins.png") }],
  "zach_edey": [{ team: "mem", image: require("../assets/images/nba-players/mem/zach_edey.png") }],
  "zach_lavine": [{ team: "chi", image: require("../assets/images/nba-players/chi/zach_lavine.png") }, { team: "sac", image: require("../assets/images/nba-players/sac/zach_lavine.png") }],
  "zeke_nnaji": [{ team: "den", image: require("../assets/images/nba-players/den/zeke_nnaji.png") }],
  "zhaire_smith": [{ team: "cle", image: require("../assets/images/nba-players/cle/zhaire_smith.png") }],
  "ziaire_williams": [{ team: "bkn", image: require("../assets/images/nba-players/bkn/ziaire_williams.png") }],
  "zion_williamson": [{ team: "nop", image: require("../assets/images/nba-players/nop/zion_williamson.png") }],
  "zyon_pullin": [{ team: "mia", image: require("../assets/images/nba-players/mia/zyon_pullin.png") }],
};

/**
 * Get a player's headshot image.
 *
 * @param playerName - Display name from API, e.g. "LeBron James"
 * @param teamAbbrev - Optional team abbreviation, e.g. "LAL", "BKN"
 * @returns The require() image source, or null if not found
 */
export const getPlayerImage = (
  playerName: string,
  teamAbbrev?: string
): any | null => {
  const normalized = normalizePlayerName(playerName);
  const entries = PLAYER_IMAGES[normalized];

  if (!entries || entries.length === 0) {
    return null;
  }

  // If team abbreviation provided, try to find a match for that team
  if (teamAbbrev) {
    const teamCode =
      TEAM_ABBREV_MAP[teamAbbrev.toUpperCase()] || teamAbbrev.toLowerCase();
    const teamMatch = entries.find((e) => e.team === teamCode);
    if (teamMatch) {
      return teamMatch.image;
    }
  }

  // Fall back to first available entry
  return entries[0].image;
};

/**
 * Check if we have a local image for a given player.
 */
export const hasPlayerImage = (
  playerName: string,
  teamAbbrev?: string
): boolean => {
  return getPlayerImage(playerName, teamAbbrev) !== null;
};

/**
 * Get all available team codes for a player (useful for debugging).
 */
export const getPlayerTeams = (playerName: string): string[] => {
  const normalized = normalizePlayerName(playerName);
  const entries = PLAYER_IMAGES[normalized];
  if (!entries) return [];
  return entries.map((e) => e.team);
};
