// NBA Team Logos
export const getNBATeamLogo = (teamName: string) => {
  const logoMap: { [key: string]: any } = {
    "Atlanta Hawks": require("../assets/images/team-logos/nba/atlanta_hawks.png"),
    "Boston Celtics": require("../assets/images/team-logos/nba/boston_celtics.png"),
    "Brooklyn Nets": require("../assets/images/team-logos/nba/brooklyn_nets.png"),
    "Charlotte Hornets": require("../assets/images/team-logos/nba/charlotte_hornets.png"),
    "Chicago Bulls": require("../assets/images/team-logos/nba/chicago_bulls.png"),
    "Cleveland Cavaliers": require("../assets/images/team-logos/nba/cleveland_cavaliers.png"),
    "Dallas Mavericks": require("../assets/images/team-logos/nba/dallas_mavericks.png"),
    "Denver Nuggets": require("../assets/images/team-logos/nba/denver_nuggets.png"),
    "Detroit Pistons": require("../assets/images/team-logos/nba/detroit_pistons.png"),
    "Golden State Warriors": require("../assets/images/team-logos/nba/golden_state_warriors.png"),
    "Houston Rockets": require("../assets/images/team-logos/nba/houston_rockets.png"),
    "Indiana Pacers": require("../assets/images/team-logos/nba/indiana_pacers.png"),
    "LA Clippers": require("../assets/images/team-logos/nba/los_angeles_clippers.png"),
    "Los Angeles Lakers": require("../assets/images/team-logos/nba/los_angeles_lakers.png"),
    "Memphis Grizzlies": require("../assets/images/team-logos/nba/memphis_grizzlies.png"),
    "Miami Heat": require("../assets/images/team-logos/nba/miami_heat.png"),
    "Milwaukee Bucks": require("../assets/images/team-logos/nba/milwaukee_bucks.png"),
    "Minnesota Timberwolves": require("../assets/images/team-logos/nba/minnesota_timberwolves.png"),
    "New Orleans Pelicans": require("../assets/images/team-logos/nba/new_orleans_pelicans.png"),
    "New York Knicks": require("../assets/images/team-logos/nba/new_york_knicks.png"),
    "Oklahoma City Thunder": require("../assets/images/team-logos/nba/oklahoma_city_thunder.png"),
    "Orlando Magic": require("../assets/images/team-logos/nba/orlando_magic.png"),
    "Philadelphia 76ers": require("../assets/images/team-logos/nba/philadelphia_76ers.png"),
    "Phoenix Suns": require("../assets/images/team-logos/nba/phoenix_suns.png"),
    "Portland Trail Blazers": require("../assets/images/team-logos/nba/portland_trail_blazers.png"),
    "Sacramento Kings": require("../assets/images/team-logos/nba/sacramento_kings.png"),
    "San Antonio Spurs": require("../assets/images/team-logos/nba/san_antonio_spurs.png"),
    "Toronto Raptors": require("../assets/images/team-logos/nba/toronto_raptors.png"),
    "Utah Jazz": require("../assets/images/team-logos/nba/utah_jazz.png"),
    "Washington Wizards": require("../assets/images/team-logos/nba/washington_wizards.png"),
  };

  return logoMap[teamName] || require("../assets/images/logo.png");
};

// NFL Team Logos
export const getNFLTeamLogo = (teamName: string) => {
  const logoMap: { [key: string]: any } = {
    "Arizona Cardinals": require("../assets/images/team-logos/nfl/arizona_cardinals.png"),
    "Atlanta Falcons": require("../assets/images/team-logos/nfl/atlanta_falcons.png"),
    "Baltimore Ravens": require("../assets/images/team-logos/nfl/baltimore_ravens.png"),
    "Buffalo Bills": require("../assets/images/team-logos/nfl/buffalo_bills.png"),
    "Carolina Panthers": require("../assets/images/team-logos/nfl/carolina_panthers.png"),
    "Chicago Bears": require("../assets/images/team-logos/nfl/chicago_bears.png"),
    "Cincinnati Bengals": require("../assets/images/team-logos/nfl/cincinnati_bengals.png"),
    "Cleveland Browns": require("../assets/images/team-logos/nfl/cleveland_browns.png"),
    "Dallas Cowboys": require("../assets/images/team-logos/nfl/dallas_cowboys.png"),
    "Denver Broncos": require("../assets/images/team-logos/nfl/denver_broncos.png"),
    "Detroit Lions": require("../assets/images/team-logos/nfl/detroit_lions.png"),
    "Green Bay Packers": require("../assets/images/team-logos/nfl/green_bay_packers.png"),
    "Houston Texans": require("../assets/images/team-logos/nfl/houston_texans.png"),
    "Indianapolis Colts": require("../assets/images/team-logos/nfl/indianapolis_colts.png"),
    "Jacksonville Jaguars": require("../assets/images/team-logos/nfl/jacksonville_jaguars.png"),
    "Kansas City Chiefs": require("../assets/images/team-logos/nfl/kansas_city_chiefs.png"),
    "Las Vegas Raiders": require("../assets/images/team-logos/nfl/las_vegas_raiders.png"),
    "Los Angeles Chargers": require("../assets/images/team-logos/nfl/los_angeles_chargers.png"),
    "Los Angeles Rams": require("../assets/images/team-logos/nfl/los_angeles_rams.png"),
    "Miami Dolphins": require("../assets/images/team-logos/nfl/miami_dolphins.png"),
    "Minnesota Vikings": require("../assets/images/team-logos/nfl/minnesota_vikings.png"),
    "New England Patriots": require("../assets/images/team-logos/nfl/new_england_patriots.png"),
    "New Orleans Saints": require("../assets/images/team-logos/nfl/new_orleans_saints.png"),
    "New York Giants": require("../assets/images/team-logos/nfl/new_york_giants.png"),
    "New York Jets": require("../assets/images/team-logos/nfl/new_york_jets.png"),
    "Philadelphia Eagles": require("../assets/images/team-logos/nfl/philadelphia_eagles.png"),
    "Pittsburgh Steelers": require("../assets/images/team-logos/nfl/pittsburgh_steelers.png"),
    "San Francisco 49ers": require("../assets/images/team-logos/nfl/san_francisco_49ers.png"),
    "Seattle Seahawks": require("../assets/images/team-logos/nfl/seattle_seahawks.png"),
    "Tampa Bay Buccaneers": require("../assets/images/team-logos/nfl/tampa_bay_buccaneers.png"),
    "Tennessee Titans": require("../assets/images/team-logos/nfl/tennessee_titans.png"),
    "Washington Commanders": require("../assets/images/team-logos/nfl/washington_commanders.png"),
  };

  return logoMap[teamName] || null;
};

// Soccer Team Logos
export const getSoccerTeamLogo = (teamName: string) => {
  const logoMap: { [key: string]: any } = {
    // English Premier League
    "Arsenal": require("../assets/images/team-logos/soccer/arsenal_fc.png"),
    "Aston Villa": require("../assets/images/team-logos/soccer/aston_villa.png"),
    "AFC Bournemouth": require("../assets/images/team-logos/soccer/afc_bournemouth.png"),
    "Brentford": require("../assets/images/team-logos/soccer/brentford_fc.png"),
    "Brighton & Hove Albion": require("../assets/images/team-logos/soccer/brighton_hove_albion.png"),
    "Burnley": require("../assets/images/team-logos/soccer/burnley_fc.png"),
    "Chelsea": require("../assets/images/team-logos/soccer/chelsea_fc.png"),
    "Crystal Palace": require("../assets/images/team-logos/soccer/crystal_palace.png"),
    "Everton": require("../assets/images/team-logos/soccer/everton_fc.png"),
    "Fulham": require("../assets/images/team-logos/soccer/fulham_fc.png"),
    "Leeds United": require("../assets/images/team-logos/soccer/leeds_united.png"),
    "Liverpool": require("../assets/images/team-logos/soccer/liverpool_fc.png"),
    "Manchester City": require("../assets/images/team-logos/soccer/manchester_city.png"),
    "Manchester United": require("../assets/images/team-logos/soccer/manchester_united.png"),
    "Newcastle United": require("../assets/images/team-logos/soccer/newcastle_united.png"),
    "Nottingham Forest": require("../assets/images/team-logos/soccer/nottingham_forest.png"),
    "Tottenham Hotspur": require("../assets/images/team-logos/soccer/tottenham_hotspur.png"),
    "West Ham United": require("../assets/images/team-logos/soccer/west_ham_united.png"),
    "Wolverhampton Wanderers": require("../assets/images/team-logos/soccer/wolverhampton_wanderers.png"),

    // La Liga
    "Barcelona": require("../assets/images/team-logos/soccer/fc_barcelona.png"),
    "Real Madrid": require("../assets/images/team-logos/soccer/real_madrid.png"),
    "Atlético de Madrid": require("../assets/images/team-logos/soccer/atlético_de_madrid.png"),
    "Sevilla": require("../assets/images/team-logos/soccer/sevilla_fc.png"),
    "Valencia": require("../assets/images/team-logos/soccer/valencia_cf.png"),
    "Villarreal": require("../assets/images/team-logos/soccer/villarreal_cf.png"),
    "Real Betis Balompié": require("../assets/images/team-logos/soccer/real_betis_balompié.png"),
    "Athletic Bilbao": require("../assets/images/team-logos/soccer/athletic_bilbao.png"),
    "Real Sociedad": require("../assets/images/team-logos/soccer/real_sociedad.png"),
    "Getafe": require("../assets/images/team-logos/soccer/getafe_cf.png"),
    "CA Osasuna": require("../assets/images/team-logos/soccer/ca_osasuna.png"),
    "Celta de Vigo": require("../assets/images/team-logos/soccer/celta_de_vigo.png"),
    "Rayo Vallecano": require("../assets/images/team-logos/soccer/rayo_vallecano.png"),
    "RCD Espanyol Barcelona": require("../assets/images/team-logos/soccer/rcd_espanyol_barcelona.png"),
    "RCD Mallorca": require("../assets/images/team-logos/soccer/rcd_mallorca.png"),
    "Girona": require("../assets/images/team-logos/soccer/girona_fc.png"),
    "Deportivo Alavés": require("../assets/images/team-logos/soccer/deportivo_alavés.png"),

    // Serie A
    "AC Milan": require("../assets/images/team-logos/soccer/ac_milan.png"),
    "Inter Milan": require("../assets/images/team-logos/soccer/inter_milan.png"),
    "Juventus FC": require("../assets/images/team-logos/soccer/juventus_fc.png"),
    "AS Roma": require("../assets/images/team-logos/soccer/as_roma.png"),
    "SS Lazio": require("../assets/images/team-logos/soccer/ss_lazio.png"),
    "SSC Napoli": require("../assets/images/team-logos/soccer/ssc_napoli.png"),
    "Atalanta BC": require("../assets/images/team-logos/soccer/atalanta_bc.png"),
    "ACF Fiorentina": require("../assets/images/team-logos/soccer/acf_fiorentina.png"),
    "Bologna FC 1909": require("../assets/images/team-logos/soccer/bologna_fc_1909.png"),
    "Torino FC": require("../assets/images/team-logos/soccer/torino_fc.png"),
    "Hellas Verona": require("../assets/images/team-logos/soccer/hellas_verona.png"),
    "Udinese Calcio": require("../assets/images/team-logos/soccer/udinese_calcio.png"),
    "US Sassuolo": require("../assets/images/team-logos/soccer/us_sassuolo.png"),
    "US Lecce": require("../assets/images/team-logos/soccer/us_lecce.png"),
    "Genoa CFC": require("../assets/images/team-logos/soccer/genoa_cfc.png"),
    "Como 1907": require("../assets/images/team-logos/soccer/como_1907.png"),
    "Parma Calcio 1913": require("../assets/images/team-logos/soccer/parma_calcio_1913.png"),
    "Cagliari Calcio": require("../assets/images/team-logos/soccer/cagliari_calcio.png"),

    // Bundesliga
    "Bayern Munich": require("../assets/images/team-logos/soccer/bayern_munich.png"),
    "Borussia Dortmund": require("../assets/images/team-logos/soccer/borussia_dortmund.png"),
    "RB Leipzig": require("../assets/images/team-logos/soccer/rb_leipzig.png"),
    "Bayer 04 Leverkusen": require("../assets/images/team-logos/soccer/bayer_04_leverkusen.png"),
    "Borussia Mönchengladbach": require("../assets/images/team-logos/soccer/borussia_mönchengladbach.png"),
    "Eintracht Frankfurt": require("../assets/images/team-logos/soccer/eintracht_frankfurt.png"),
    "VfL Wolfsburg": require("../assets/images/team-logos/soccer/vfl_wolfsburg.png"),
    "VfB Stuttgart": require("../assets/images/team-logos/soccer/vfb_stuttgart.png"),
    "SC Freiburg": require("../assets/images/team-logos/soccer/sc_freiburg.png"),
    "TSG 1899 Hoffenheim": require("../assets/images/team-logos/soccer/tsg_1899_hoffenheim.png"),
    "1. FC Union Berlin": require("../assets/images/team-logos/soccer/1_fc_union_berlin.png"),
    "1. FSV Mainz 05": require("../assets/images/team-logos/soccer/1_fsv_mainz_05.png"),
    "1. FC Köln": require("../assets/images/team-logos/soccer/1_fc_köln.png"),
    "SV Werder Bremen": require("../assets/images/team-logos/soccer/sv_werder_bremen.png"),
    "FC Augsburg": require("../assets/images/team-logos/soccer/fc_augsburg.png"),
    "FC St. Pauli": require("../assets/images/team-logos/soccer/fc_st_pauli.png"),
    "1. FC Heidenheim 1846": require("../assets/images/team-logos/soccer/1_fc_heidenheim_1846.png"),
    "Hamburger SV": require("../assets/images/team-logos/soccer/hamburger_sv.png"),

    // Ligue 1
    "Paris Saint-Germain": require("../assets/images/team-logos/soccer/paris_saint_germain.png"),
    "Olympique Lyon": require("../assets/images/team-logos/soccer/olympique_lyon.png"),
    "Olympique Marseille": require("../assets/images/team-logos/soccer/olympique_marseille.png"),
    "AS Monaco": require("../assets/images/team-logos/soccer/as_monaco.png"),
    "LOSC Lille": require("../assets/images/team-logos/soccer/losc_lille.png"),
    "OGC Nice": require("../assets/images/team-logos/soccer/ogc_nice.png"),
    "Stade Rennais FC": require("../assets/images/team-logos/soccer/stade_rennais_fc.png"),
    "RC Lens": require("../assets/images/team-logos/soccer/rc_lens.png"),
    "RC Strasbourg Alsace": require("../assets/images/team-logos/soccer/rc_strasbourg_alsace.png"),
    "FC Nantes": require("../assets/images/team-logos/soccer/fc_nantes.png"),
    "Stade Brestois 29": require("../assets/images/team-logos/soccer/stade_brestois_29.png"),
    "FC Toulouse": require("../assets/images/team-logos/soccer/fc_toulouse.png"),
    "Le Havre AC": require("../assets/images/team-logos/soccer/le_havre_ac.png"),
    "AJ Auxerre": require("../assets/images/team-logos/soccer/aj_auxerre.png"),
    "Angers SCO": require("../assets/images/team-logos/soccer/angers_sco.png"),
    "FC Lorient": require("../assets/images/team-logos/soccer/fc_lorient.png"),
    "FC Metz": require("../assets/images/team-logos/soccer/fc_metz.png"),
    "Paris FC": require("../assets/images/team-logos/soccer/paris_fc.png"),
  };

  return logoMap[teamName] || require("../assets/images/logo.png");
};

