// Helper function to normalize team names to filename format
const normalizeTeamName = (name: string): string => {
  return name
    .toLowerCase()
    .replace(/\s+/g, "_")
    .replace(/[^a-z0-9_]/g, "")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "");
};

// NBA Team Logos - Prefer SVG, fallback to PNG
export const getNBATeamLogo = (teamName: string) => {
  const logoMap: { [key: string]: any } = {
    // Main NBA teams - prefer SVG
    "Atlanta Hawks": require("../assets/images/team-logos/nba/atlanta_hawks.svg"),
    "Boston Celtics": require("../assets/images/team-logos/nba/boston_celtics.svg"),
    "Brooklyn Nets": require("../assets/images/team-logos/nba/brooklyn_nets.svg"),
    "Charlotte Hornets": require("../assets/images/team-logos/nba/charlotte_hornets.svg"),
    "Chicago Bulls": require("../assets/images/team-logos/nba/chicago_bulls.svg"),
    "Cleveland Cavaliers": require("../assets/images/team-logos/nba/cleveland_cavaliers.svg"),
    "Dallas Mavericks": require("../assets/images/team-logos/nba/dallas_mavericks.svg"),
    "Denver Nuggets": require("../assets/images/team-logos/nba/denver_nuggets.svg"),
    "Detroit Pistons": require("../assets/images/team-logos/nba/detroit_pistons.svg"),
    "Golden State Warriors": require("../assets/images/team-logos/nba/golden_state_warriors.svg"),
    "Houston Rockets": require("../assets/images/team-logos/nba/houston_rockets.svg"),
    "Indiana Pacers": require("../assets/images/team-logos/nba/indiana_pacers.svg"),
    "LA Clippers": require("../assets/images/team-logos/nba/la_clippers.svg"),
    "Los Angeles Lakers": require("../assets/images/team-logos/nba/los_angeles_lakers.svg"),
    "Memphis Grizzlies": require("../assets/images/team-logos/nba/memphis_grizzlies.svg"),
    "Miami Heat": require("../assets/images/team-logos/nba/miami_heat.svg"),
    "Milwaukee Bucks": require("../assets/images/team-logos/nba/milwaukee_bucks.svg"),
    "Minnesota Timberwolves": require("../assets/images/team-logos/nba/minnesota_timberwolves.svg"),
    "New Orleans Pelicans": require("../assets/images/team-logos/nba/new_orleans_pelicans.svg"),
    "New York Knicks": require("../assets/images/team-logos/nba/new_york_knicks.svg"),
    "Oklahoma City Thunder": require("../assets/images/team-logos/nba/oklahoma_city_thunder.svg"),
    "Orlando Magic": require("../assets/images/team-logos/nba/orlando_magic.svg"),
    "Philadelphia 76ers": require("../assets/images/team-logos/nba/philadelphia_76ers.svg"),
    "Phoenix Suns": require("../assets/images/team-logos/nba/phoenix_suns.svg"),
    "Portland Trail Blazers": require("../assets/images/team-logos/nba/portland_trail_blazers.svg"),
    "Sacramento Kings": require("../assets/images/team-logos/nba/sacramento_kings.svg"),
    "San Antonio Spurs": require("../assets/images/team-logos/nba/san_antonio_spurs.svg"),
    "Toronto Raptors": require("../assets/images/team-logos/nba/toronto_raptors.svg"),
    "Utah Jazz": require("../assets/images/team-logos/nba/utah_jazz.png"),
    "Washington Wizards": require("../assets/images/team-logos/nba/washington_wizards.svg"),

    // International/Other teams
    "Brisbane Bullets": require("../assets/images/team-logos/nba/brisbane_bullets.svg"),
    "Guangzhou Long-Lions": require("../assets/images/team-logos/nba/guangzhou_longlions.svg"),
    "Haifa Maccabi Haifa": require("../assets/images/team-logos/nba/haifa_maccabi_haifa.png"),
    "Melbourne United": require("../assets/images/team-logos/nba/melbourne_united.png"),
    "Shanghai Sharks": require("../assets/images/team-logos/nba/shanghai_sharks.png"),
    "Sydney Kings": require("../assets/images/team-logos/nba/sydney_kings.svg"),
    "Adelaide 36ers": require("../assets/images/team-logos/nba/adelaide_36ers.svg"),
    "Beijing Ducks": require("../assets/images/team-logos/nba/beijing_ducks.png"),
    "New Zealand Breakers": require("../assets/images/team-logos/nba/new_zealand_breakers.svg"),
    "Perth Wildcats": require("../assets/images/team-logos/nba/perth_wildcats.png"),
    "Cairns Taipans": require("../assets/images/team-logos/nba/cairns_taipans.svg"),
    "Ra'anana Maccabi Ra'anana": require("../assets/images/team-logos/nba/raanana_maccabi_raanana.png"),

    // Special teams
    "Team Team Durant": require("../assets/images/team-logos/nba/team_team_durant.png"),
    "Team LeBron": require("../assets/images/team-logos/nba/team_usa.svg"),
    "Away Team Wilbon": require("../assets/images/team-logos/nba/away_team_wilbon.svg"),
    "Home Team Stephen A": require("../assets/images/team-logos/nba/team_usa.svg"),
    "USA USA": require("../assets/images/team-logos/nba/usa_usa.png"),
    "Team Africa": require("../assets/images/team-logos/nba/team_africa.svg"),
    "Team World": require("../assets/images/team-logos/nba/team_usa.svg"),
    "World World": require("../assets/images/team-logos/nba/team_usa.svg"),
    "Team USA": require("../assets/images/team-logos/nba/team_usa.svg"),
    "Team China": require("../assets/images/team-logos/nba/team_china.svg"),
    "Team Croatia": require("../assets/images/team-logos/nba/team_croatia.svg"),
    "Franca Franca": require("../assets/images/team-logos/nba/franca_franca.png"),
    "Utah Blue": require("../assets/images/team-logos/nba/utah_blue.png"),
    "Utah White": require("../assets/images/team-logos/nba/utah_white.png"),

    // International basketball teams
    "Paschoalotto/Bauru": require("../assets/images/team-logos/nba/paschoalotto_bauru.png"),
    "Fenerbahce Sports Club": require("../assets/images/team-logos/nba/fenerbahce_sports_club.svg"),
    "Olimpia Milano": require("../assets/images/team-logos/nba/olimpia_milano.svg"),
    "Real Madrid Real Madrid": require("../assets/images/team-logos/nba/real_madrid_real_madrid.png"),
    "Rio de Janeiro Flamengo": require("../assets/images/team-logos/nba/rio_de_janeiro_flamengo.svg"),
    "Barcelona FC Barcelona": require("../assets/images/team-logos/nba/barcelona_fc_barcelona.svg"),
    "Buenos Aires San Lorenzo": require("../assets/images/team-logos/nba/buenos_aires_san_lorenzo.svg"),
    "Flamengo": require("../assets/images/team-logos/nba/flamengo.svg"),
  };

  return logoMap[teamName] || require("../assets/images/logo.png");
};

// NFL Team Logos - Prefer SVG, fallback to PNG
export const getNFLTeamLogo = (teamName: string) => {
  const logoMap: { [key: string]: any } = {
    // Main NFL teams - prefer SVG
    "Arizona Cardinals": require("../assets/images/team-logos/nfl/arizona_cardinals.svg"),
    "Atlanta Falcons": require("../assets/images/team-logos/nfl/atlanta_falcons.svg"),
    "Baltimore Ravens": require("../assets/images/team-logos/nfl/baltimore_ravens.png"),
    "Buffalo Bills": require("../assets/images/team-logos/nfl/buffalo_bills.png"),
    "Carolina Panthers": require("../assets/images/team-logos/nfl/carolina_panthers.svg"),
    "Chicago Bears": require("../assets/images/team-logos/nfl/chicago_bears.svg"),
    "Cincinnati Bengals": require("../assets/images/team-logos/nfl/cincinnati_bengals.svg"),
    "Cleveland Browns": require("../assets/images/team-logos/nfl/cleveland_browns.svg"),
    "Dallas Cowboys": require("../assets/images/team-logos/nfl/dallas_cowboys.svg"),
    "Denver Broncos": require("../assets/images/team-logos/nfl/denver_broncos.svg"),
    "Detroit Lions": require("../assets/images/team-logos/nfl/detroit_lions.svg"),
    "Green Bay Packers": require("../assets/images/team-logos/nfl/green_bay_packers.svg"),
    "Houston Texans": require("../assets/images/team-logos/nfl/houston_texans.png"),
    "Indianapolis Colts": require("../assets/images/team-logos/nfl/indianapolis_colts.svg"),
    "Jacksonville Jaguars": require("../assets/images/team-logos/nfl/jacksonville_jaguars.svg"),
    "Kansas City Chiefs": require("../assets/images/team-logos/nfl/kansas_city_chiefs.svg"),
    "Las Vegas Raiders": require("../assets/images/team-logos/nfl/las_vegas_raiders.svg"),
    "Los Angeles Chargers": require("../assets/images/team-logos/nfl/los_angeles_chargers.png"),
    "Los Angeles Rams": require("../assets/images/team-logos/nfl/los_angeles_rams.svg"),
    "Miami Dolphins": require("../assets/images/team-logos/nfl/miami_dolphins.svg"),
    "Minnesota Vikings": require("../assets/images/team-logos/nfl/minnesota_vikings.svg"),
    "New England Patriots": require("../assets/images/team-logos/nfl/new_england_patriots.png"),
    "New Orleans Saints": require("../assets/images/team-logos/nfl/new_orleans_saints.svg"),
    "New York Giants": require("../assets/images/team-logos/nfl/new_york_giants.svg"),
    "New York Jets": require("../assets/images/team-logos/nfl/new_york_jets.svg"),
    "Philadelphia Eagles": require("../assets/images/team-logos/nfl/philadelphia_eagles.svg"),
    "Pittsburgh Steelers": require("../assets/images/team-logos/nfl/pittsburgh_steelers.svg"),
    "San Francisco 49ers": require("../assets/images/team-logos/nfl/san_francisco_49ers.svg"),
    "Seattle Seahawks": require("../assets/images/team-logos/nfl/seattle_seahawks.png"),
    "Tampa Bay Buccaneers": require("../assets/images/team-logos/nfl/tampa_bay_buccaneers.svg"),
    "Tennessee Titans": require("../assets/images/team-logos/nfl/tennessee_titans.svg"),
    "Washington Commanders": require("../assets/images/team-logos/nfl/washington_commanders.svg"),

    // Conference logos
    "NFC": require("../assets/images/team-logos/nfl/nfc.svg"),
    "AFC": require("../assets/images/team-logos/nfl/afc.svg"),
  };

  return logoMap[teamName] || require("../assets/images/logo.png");
};

// Soccer Team Logos - Prefer SVG, fallback to PNG
export const getSoccerTeamLogo = (teamName: string) => {
  const logoMap: { [key: string]: any } = {
    // English Premier League - prefer SVG
    "Arsenal": require("../assets/images/team-logos/soccer/arsenal_fc.png"),
    "Aston Villa": require("../assets/images/team-logos/soccer/aston_villa.svg"),
    "Bournemouth": require("../assets/images/team-logos/soccer/bournemouth.svg"),
    "Brentford": require("../assets/images/team-logos/soccer/brentford_fc.png"),
    "Brighton": require("../assets/images/team-logos/soccer/brighton.svg"),
    "Burnley": require("../assets/images/team-logos/soccer/burnley_fc.png"),
    "Chelsea": require("../assets/images/team-logos/soccer/chelsea.svg"),
    "Crystal Palace": require("../assets/images/team-logos/soccer/crystal_palace.svg"),
    "Everton": require("../assets/images/team-logos/soccer/everton.svg"),
    "Fulham": require("../assets/images/team-logos/soccer/fulham.svg"),
    "Leicester": require("../assets/images/team-logos/soccer/leicester.svg"),
    "Liverpool": require("../assets/images/team-logos/soccer/liverpool_fc.png"),
    "Manchester City": require("../assets/images/team-logos/soccer/manchester_city.svg"),
    "Manchester United": require("../assets/images/team-logos/soccer/manchester_united.svg"),
    "Newcastle": require("../assets/images/team-logos/soccer/newcastle_united.png"),
    "Nottingham Forest": require("../assets/images/team-logos/soccer/nottingham_forest.svg"),
    "Tottenham": require("../assets/images/team-logos/soccer/tottenham.svg"),
    "West Ham": require("../assets/images/team-logos/soccer/west_ham.svg"),
    "Wolves": require("../assets/images/team-logos/soccer/wolverhampton_wanderers.png"),
    "Ipswich": require("../assets/images/team-logos/soccer/ipswich.svg"),
    "Southampton": require("../assets/images/team-logos/soccer/southampton.svg"),

    // La Liga - prefer SVG
    "Barcelona": require("../assets/images/team-logos/soccer/barcelona.svg"),
    "Real Madrid": require("../assets/images/team-logos/soccer/real_madrid.svg"),
    "Atletico Madrid": require("../assets/images/team-logos/soccer/atletico_madrid.svg"),
    "Sevilla": require("../assets/images/team-logos/soccer/sevilla.svg"),
    "Valencia": require("../assets/images/team-logos/soccer/valencia.svg"),
    "Villarreal": require("../assets/images/team-logos/soccer/villarreal.svg"),
    "Real Betis": require("../assets/images/team-logos/soccer/real_betis.svg"),
    "Athletic Club": require("../assets/images/team-logos/soccer/athletic_club.svg"),
    "Real Sociedad": require("../assets/images/team-logos/soccer/real_sociedad.svg"),
    "Getafe": require("../assets/images/team-logos/soccer/getafe.svg"),
    "Osasuna": require("../assets/images/team-logos/soccer/osasuna.svg"),
    "Celta Vigo": require("../assets/images/team-logos/soccer/celta_vigo.svg"),
    "Rayo Vallecano": require("../assets/images/team-logos/soccer/rayo_vallecano.svg"),
    "Espanyol": require("../assets/images/team-logos/soccer/espanyol.svg"),
    "Mallorca": require("../assets/images/team-logos/soccer/mallorca.svg"),
    "Girona": require("../assets/images/team-logos/soccer/girona.svg"),
    "Alaves": require("../assets/images/team-logos/soccer/alaves.svg"),
    "Las Palmas": require("../assets/images/team-logos/soccer/las_palmas.svg"),
    "Leganes": require("../assets/images/team-logos/soccer/leganes.svg"),
    "Valladolid": require("../assets/images/team-logos/soccer/valladolid.svg"),

    // Serie A - prefer SVG
    "AC Milan": require("../assets/images/team-logos/soccer/ac_milan.svg"),
    "Inter Milan": require("../assets/images/team-logos/soccer/inter_milan.svg"),
    "Juventus": require("../assets/images/team-logos/soccer/juventus.svg"),
    "AS Roma": require("../assets/images/team-logos/soccer/as_roma.svg"),
    "Lazio": require("../assets/images/team-logos/soccer/lazio.svg"),
    "Napoli": require("../assets/images/team-logos/soccer/napoli.svg"),
    "Atalanta": require("../assets/images/team-logos/soccer/atalanta.svg"),
    "Fiorentina": require("../assets/images/team-logos/soccer/fiorentina.svg"),
    "Bologna": require("../assets/images/team-logos/soccer/bologna_fc_1909.png"),
    "Torino": require("../assets/images/team-logos/soccer/torino.svg"),
    "Verona": require("../assets/images/team-logos/soccer/verona.svg"),
    "Udinese": require("../assets/images/team-logos/soccer/udinese.svg"),
    "Empoli": require("../assets/images/team-logos/soccer/empoli.svg"),
    "Lecce": require("../assets/images/team-logos/soccer/lecce.svg"),
    "Genoa": require("../assets/images/team-logos/soccer/genoa.svg"),
    "Como": require("../assets/images/team-logos/soccer/como.svg"),
    "Parma": require("../assets/images/team-logos/soccer/parma.svg"),
    "Cagliari": require("../assets/images/team-logos/soccer/cagliari_calcio.png"),
    "Monza": require("../assets/images/team-logos/soccer/monza.svg"),
    "Venezia": require("../assets/images/team-logos/soccer/venezia.svg"),

    // Bundesliga - prefer SVG
    "Bayern München": require("../assets/images/team-logos/soccer/bayern_mnchen.svg"),
    "Borussia Dortmund": require("../assets/images/team-logos/soccer/borussia_dortmund.svg"),
    "RB Leipzig": require("../assets/images/team-logos/soccer/rb_leipzig.svg"),
    "Bayer Leverkusen": require("../assets/images/team-logos/soccer/bayer_leverkusen.svg"),
    "Borussia Mönchengladbach": require("../assets/images/team-logos/soccer/borussia_mnchengladbach.svg"),
    "Eintracht Frankfurt": require("../assets/images/team-logos/soccer/eintracht_frankfurt.svg"),
    "VfL Wolfsburg": require("../assets/images/team-logos/soccer/vfl_wolfsburg.svg"),
    "VfB Stuttgart": require("../assets/images/team-logos/soccer/vfb_stuttgart.svg"),
    "SC Freiburg": require("../assets/images/team-logos/soccer/sc_freiburg.svg"),
    "1899 Hoffenheim": require("../assets/images/team-logos/soccer/1899_hoffenheim.svg"),
    "Union Berlin": require("../assets/images/team-logos/soccer/union_berlin.svg"),
    "FSV Mainz 05": require("../assets/images/team-logos/soccer/fsv_mainz_05.svg"),
    "FC Augsburg": require("../assets/images/team-logos/soccer/fc_augsburg.svg"),
    "FC St. Pauli": require("../assets/images/team-logos/soccer/fc_st_pauli.svg"),
    "1. FC Heidenheim": require("../assets/images/team-logos/soccer/1_fc_heidenheim.svg"),
    "Werder Bremen": require("../assets/images/team-logos/soccer/werder_bremen.svg"),
    "VfL Bochum": require("../assets/images/team-logos/soccer/vfl_bochum.svg"),
    "Holstein Kiel": require("../assets/images/team-logos/soccer/holstein_kiel.svg"),

    // Ligue 1 - prefer SVG
    "Paris Saint Germain": require("../assets/images/team-logos/soccer/paris_saint_germain.svg"),
    "Lyon": require("../assets/images/team-logos/soccer/lyon.svg"),
    "Marseille": require("../assets/images/team-logos/soccer/marseille.svg"),
    "Monaco": require("../assets/images/team-logos/soccer/monaco.svg"),
    "Lille": require("../assets/images/team-logos/soccer/lille.svg"),
    "Nice": require("../assets/images/team-logos/soccer/nice.svg"),
    "Rennes": require("../assets/images/team-logos/soccer/rennes.svg"),
    "Lens": require("../assets/images/team-logos/soccer/lens.svg"),
    "Strasbourg": require("../assets/images/team-logos/soccer/strasbourg.svg"),
    "Nantes": require("../assets/images/team-logos/soccer/nantes.svg"),
    "Stade Brestois 29": require("../assets/images/team-logos/soccer/stade_brestois_29.svg"),
    "Toulouse": require("../assets/images/team-logos/soccer/toulouse.svg"),
    "LE Havre": require("../assets/images/team-logos/soccer/le_havre.svg"),
    "Auxerre": require("../assets/images/team-logos/soccer/auxerre.svg"),
    "Angers": require("../assets/images/team-logos/soccer/angers.svg"),
    "Lorient": require("../assets/images/team-logos/soccer/lorient.svg"),
    "Saint Etienne": require("../assets/images/team-logos/soccer/saint_etienne.svg"),

    // Portuguese League
    "Benfica": require("../assets/images/team-logos/soccer/benfica.svg"),
    "FC Porto": require("../assets/images/team-logos/soccer/fc_porto.svg"),
    "Sporting CP": require("../assets/images/team-logos/soccer/sporting_cp.svg"),
    "SC Braga": require("../assets/images/team-logos/soccer/sc_braga.svg"),
    "Boavista": require("../assets/images/team-logos/soccer/boavista.svg"),
    "Guimaraes": require("../assets/images/team-logos/soccer/guimaraes.svg"),
    "Nacional": require("../assets/images/team-logos/soccer/cd_nacional.png"),
    "Rio Ave": require("../assets/images/team-logos/soccer/rio_ave.svg"),
    "Santa Clara": require("../assets/images/team-logos/soccer/santa_clara.svg"),
    "Estoril": require("../assets/images/team-logos/soccer/estoril.svg"),
    "Farense": require("../assets/images/team-logos/soccer/farense.png"),
    "Arouca": require("../assets/images/team-logos/soccer/arouca.png"),
    "Famalicao": require("../assets/images/team-logos/soccer/famalicao.svg"),
    "GIL Vicente": require("../assets/images/team-logos/soccer/gil_vicente_fc.png"),
    "Casa Pia": require("../assets/images/team-logos/soccer/casa_pia_ac.png"),
    "Estrela": require("../assets/images/team-logos/soccer/estrela.svg"),
    "AVS": require("../assets/images/team-logos/soccer/avs_futebol.png"),
    "Moreirense": require("../assets/images/team-logos/soccer/moreirense.svg"),

    // Eredivisie (Netherlands)
    "Ajax": require("../assets/images/team-logos/soccer/ajax.svg"),
    "PSV Eindhoven": require("../assets/images/team-logos/soccer/psv_eindhoven.svg"),
    "Feyenoord": require("../assets/images/team-logos/soccer/feyenoord.svg"),
    "AZ Alkmaar": require("../assets/images/team-logos/soccer/az_alkmaar.svg"),
    "Groningen": require("../assets/images/team-logos/soccer/fc_groningen.png"),
    "NAC Breda": require("../assets/images/team-logos/soccer/nac_breda.svg"),
    "Fortuna Sittard": require("../assets/images/team-logos/soccer/fortuna_sittard.png"),
    "Heracles": require("../assets/images/team-logos/soccer/heracles.svg"),
    "Utrecht": require("../assets/images/team-logos/soccer/utrecht.svg"),
    "Heerenveen": require("../assets/images/team-logos/soccer/heerenveen.svg"),
    "GO Ahead Eagles": require("../assets/images/team-logos/soccer/go_ahead_eagles.svg"),
    "NEC Nijmegen": require("../assets/images/team-logos/soccer/nec_nijmegen.png"),
    "Twente": require("../assets/images/team-logos/soccer/twente.svg"),
    "Waalwijk": require("../assets/images/team-logos/soccer/waalwijk.svg"),
    "Almere City FC": require("../assets/images/team-logos/soccer/almere_city_fc.png"),
    "Sparta Rotterdam": require("../assets/images/team-logos/soccer/sparta_rotterdam.svg"),
    "PEC Zwolle": require("../assets/images/team-logos/soccer/pec_zwolle.svg"),
    "Willem II": require("../assets/images/team-logos/soccer/willem_ii.svg"),

    // National Teams
    "France": require("../assets/images/team-logos/soccer/france.svg"),
    "Spain": require("../assets/images/team-logos/soccer/spain.svg"),
    "England": require("../assets/images/team-logos/soccer/england.svg"),
    "Italy": require("../assets/images/team-logos/soccer/italy.svg"),
    "Scotland": require("../assets/images/team-logos/soccer/scotland.svg"),
    "Wales": require("../assets/images/team-logos/soccer/wales.svg"),
    "Ireland": require("../assets/images/team-logos/soccer/ireland.svg"),
    "Germany": require("../assets/images/team-logos/soccer/germany.svg"),
    "Portugal": require("../assets/images/team-logos/soccer/portugal.png"),

    // Other teams
    "Urawa": require("../assets/images/team-logos/soccer/urawa.svg"),
    "River Plate": require("../assets/images/team-logos/soccer/river_plate.svg"),
    "Boca Juniors": require("../assets/images/team-logos/soccer/boca_juniors.svg"),
    "Red Bull Salzburg": require("../assets/images/team-logos/soccer/red_bull_salzburg.svg"),
    "Wydad AC": require("../assets/images/team-logos/soccer/wydad_ac.svg"),
    "ES Tunis": require("../assets/images/team-logos/soccer/es_tunis.png"),
    "Al Ahly": require("../assets/images/team-logos/soccer/al_ahly.svg"),
    "Seattle Sounders": require("../assets/images/team-logos/soccer/seattle_sounders.svg"),
    "Los Angeles FC": require("../assets/images/team-logos/soccer/los_angeles_fc.svg"),
    "Monterrey": require("../assets/images/team-logos/soccer/monterrey.svg"),
    "Pachuca": require("../assets/images/team-logos/soccer/pachuca.svg"),
    "Auckland City": require("../assets/images/team-logos/soccer/auckland_city.png"),
    "Mamelodi Sundowns": require("../assets/images/team-logos/soccer/mamelodi_sundowns.svg"),
    "Ulsan Hyundai FC": require("../assets/images/team-logos/soccer/ulsan_hyundai_fc.svg"),
    "Al Ain": require("../assets/images/team-logos/soccer/al_ain.png"),
    "Al-Hilal Saudi FC": require("../assets/images/team-logos/soccer/alhilal_saudi_fc.svg"),
    "Inter Miami": require("../assets/images/team-logos/soccer/inter_miami.svg"),
    "Kairat": require("../assets/images/team-logos/soccer/kairat.png"),

    // Brazilian teams
    "Bahia": require("../assets/images/team-logos/soccer/bahia.svg"),
    "Internacional": require("../assets/images/team-logos/soccer/internacional.svg"),
    "Botafogo": require("../assets/images/team-logos/soccer/botafogo.svg"),
    "Palmeiras": require("../assets/images/team-logos/soccer/palmeiras.svg"),
    "Fluminense": require("../assets/images/team-logos/soccer/fluminense.svg"),
    "Sao Paulo": require("../assets/images/team-logos/soccer/sao_paulo.svg"),
    "Flamengo": require("../assets/images/team-logos/soccer/flamengo.svg"),
    "Gremio": require("../assets/images/team-logos/soccer/gremio.svg"),
    "Corinthians": require("../assets/images/team-logos/soccer/corinthians.svg"),
    "Vasco DA Gama": require("../assets/images/team-logos/soccer/vasco_da_gama.png"),
    "Atletico Paranaense": require("../assets/images/team-logos/soccer/atletico_paranaense.svg"),
    "Cruzeiro": require("../assets/images/team-logos/soccer/cruzeiro.svg"),
    "Vitoria": require("../assets/images/team-logos/soccer/vitoria.svg"),
    "Criciuma": require("../assets/images/team-logos/soccer/criciuma.svg"),
    "Atletico Goianiense": require("../assets/images/team-logos/soccer/atletico_goianiense.svg"),
    "Juventude": require("../assets/images/team-logos/soccer/juventude.svg"),
    "Fortaleza EC": require("../assets/images/team-logos/soccer/fortaleza_ec.png"),
    "RB Bragantino": require("../assets/images/team-logos/soccer/rb_bragantino.svg"),
    "Atletico-MG": require("../assets/images/team-logos/soccer/atleticomg.svg"),
    "Cuiaba": require("../assets/images/team-logos/soccer/cuiaba.svg"),
  };

  return logoMap[teamName] || require("../assets/images/logo.png");
};
